"use client";

import { createContext, useContext } from "react";

export type Lang = "fr" | "en" | "es" | "it" | "pt" | "de" | "ht";
export const LANGS: Lang[] = ["fr", "en", "es", "it", "pt", "de", "ht"];

export type Translations = Record<string, Record<Lang, string>>;

export const LangContext = createContext<{
  lang: Lang;
  setLang: (l: Lang) => void;
}>({ lang: "fr", setLang: () => {} });

export function useLang() {
  return useContext(LangContext);
}

export function t(translations: Record<Lang, string>, lang: Lang): string {
  return translations[lang] || translations.fr;
}

export const UI: Translations = {
  // Nav
  "nav.home": { fr: "Accueil", en: "Home", es: "Inicio", it: "Home", pt: "Início", de: "Start", ht: "Akèy" },
  "nav.tef": { fr: "Tutorat TEF / TCF", en: "TEF / TCF Tutoring", es: "Tutoría TEF / TCF", it: "Tutoraggio TEF / TCF", pt: "Tutoria TEF / TCF", de: "TEF / TCF-Tutoring", ht: "Tutora TEF / TCF" },
  "nav.formations": { fr: "Formations", en: "Programs", es: "Programas", it: "Programmi", pt: "Programas", de: "Programme", ht: "Pwogram" },
  "nav.examens": { fr: "Examens", en: "Exams", es: "Exámenes", it: "Esami", pt: "Exames", de: "Prüfungen", ht: "Egzamen" },
  "nav.immigration": { fr: "Programmes d'immigration", en: "Immigration Programs", es: "Programas de inmigración", it: "Programmi di immigrazione", pt: "Programas de imigração", de: "Einwanderungsprogramme", ht: "Pwogram imigrasyon" },
  "legal.exam.disclaimer": { fr: "ARCADINS Training Center n'est pas l'organisme qui administre les examens officiels TEF Canada ou TCF Canada. Nous offrons de la préparation. Les candidats doivent s'inscrire auprès d'un centre d'examen officiellement autorisé.", en: "ARCADINS Training Center is not the body that administers the official TEF Canada or TCF Canada exams. We provide preparation. Candidates must register with an officially authorized exam centre.", es: "ARCADINS Training Center no es el organismo que administra los exámenes oficiales TEF Canada o TCF Canada. Ofrecemos preparación. Los candidatos deben inscribirse en un centro de examen oficialmente autorizado.", it: "ARCADINS Training Center non è l'ente che amministra gli esami ufficiali TEF Canada o TCF Canada. Offriamo preparazione. I candidati devono iscriversi presso un centro d'esame ufficialmente autorizzato.", pt: "O ARCADINS Training Center não é o organismo que administra os exames oficiais TEF Canada ou TCF Canada. Oferecemos preparação. Os candidatos devem inscrever-se num centro de exame oficialmente autorizado.", de: "ARCADINS Training Center ist nicht die Stelle, die die offiziellen Prüfungen TEF Canada oder TCF Canada durchführt. Wir bieten Vorbereitung an. Kandidaten müssen sich bei einem offiziell autorisierten Prüfungszentrum anmelden.", ht: "ARCADINS Training Center se pa òganis ki administre egzamen ofisyèl TEF Canada oswa TCF Canada. Nou ofri preparasyon. Kandida yo dwe enskri nan yon sant egzamen ki ofisyèlman otorize." },
  "legal.immigration.disclaimer": { fr: "Les informations présentées sont de nature générale et éducative. Elles ne constituent pas un avis juridique ni un conseil réglementé en immigration. Les programmes et critères peuvent changer. Vérifiez les renseignements auprès des autorités officielles ou consultez un professionnel autorisé.", en: "The information presented is general and educational in nature. It does not constitute legal advice or regulated immigration advice. Programs and criteria may change. Verify the information with the official authorities or consult an authorized professional.", es: "La información presentada es de carácter general y educativo. No constituye asesoría jurídica ni asesoramiento regulado en inmigración. Los programas y criterios pueden cambiar. Verifique la información con las autoridades oficiales o consulte a un profesional autorizado.", it: "Le informazioni presentate sono di natura generale ed educativa. Non costituiscono consulenza legale né consulenza regolamentata in materia di immigrazione. I programmi e i criteri possono cambiare. Verificate le informazioni presso le autorità ufficiali o rivolgetevi a un professionista autorizzato.", pt: "As informações apresentadas são de natureza geral e educativa. Não constituem aconselhamento jurídico nem aconselhamento regulamentado em imigração. Os programas e critérios podem mudar. Verifique as informações junto das autoridades oficiais ou consulte um profissional autorizado.", de: "Die dargestellten Informationen sind allgemeiner und bildender Natur. Sie stellen keine Rechtsberatung oder regulierte Einwanderungsberatung dar. Programme und Kriterien können sich ändern. Überprüfen Sie die Informationen bei den offiziellen Behörden oder konsultieren Sie eine autorisierte Fachperson.", ht: "Enfòmasyon yo prezante yo se yon bagay jeneral ak edikatif. Yo pa konstitye yon konsèy jiridik ni yon konsèy reglemante nan imigrasyon. Pwogram ak kritè yo ka chanje. Verifye enfòmasyon yo ak otorite ofisyèl yo oswa konsilte yon pwofesyonèl otorize." },
  "nav.tarifs": { fr: "Tarifs", en: "Pricing", es: "Precios", it: "Prezzi", pt: "Preços", de: "Preise", ht: "Pri" },
  "acc.label": { fr: "Transparence", en: "Transparency", es: "Transparencia", it: "Trasparenza", pt: "Transparência", de: "Transparenz", ht: "Transparans" },
  "acc.title": { fr: "Accréditations & reconnaissances", en: "Accreditations & recognitions", es: "Acreditaciones y reconocimientos", it: "Accreditamenti e riconoscimenti", pt: "Acreditações e reconhecimentos", de: "Akkreditierungen & Anerkennungen", ht: "Akreditasyon & rekonesans" },
  "acc.desc": { fr: "Nous ne publions ici que des reconnaissances réelles et vérifiables. Chaque badge renvoie à une source officielle. En l'absence de preuve, rien n'est affiché.", en: "We only publish real, verifiable recognitions here. Each badge links to an official source. Where there is no proof, nothing is shown.", es: "Aquí solo publicamos reconocimientos reales y verificables. Cada distintivo enlaza a una fuente oficial. Si no hay pruebas, no se muestra nada.", it: "Qui pubblichiamo solo riconoscimenti reali e verificabili. Ogni badge rimanda a una fonte ufficiale. In assenza di prove, non viene mostrato nulla.", pt: "Aqui publicamos apenas reconhecimentos reais e verificáveis. Cada selo remete para uma fonte oficial. Na ausência de prova, nada é apresentado.", de: "Wir veröffentlichen hier nur echte, überprüfbare Anerkennungen. Jedes Abzeichen verweist auf eine offizielle Quelle. Ohne Nachweis wird nichts angezeigt.", ht: "Nou pibliye isit la sèlman rekonesans reyèl ki ka verifye. Chak badj mennen nan yon sous ofisyèl. Si pa gen prèv, nou pa montre anyen." },
  "acc.empty.title": { fr: "Aucune accréditation officielle à afficher pour le moment", en: "No official accreditation to display at this time", es: "Ninguna acreditación oficial que mostrar por ahora", it: "Nessun accreditamento ufficiale da mostrare al momento", pt: "Nenhuma acreditação oficial a apresentar de momento", de: "Derzeit keine offizielle Akkreditierung anzuzeigen", ht: "Pa gen okenn akreditasyon ofisyèl pou montre kounye a" },
  "acc.empty.body": { fr: "Par honnêteté, nous n'affichons aucun logo, sceau ou label d'accréditation tant qu'il n'a pas été officiellement obtenu et qu'une preuve publique ne peut être fournie. Cette page sera mise à jour dès qu'une reconnaissance vérifiable sera disponible.", en: "In the interest of honesty, we do not display any accreditation logo, seal or label until it has been officially obtained and a public proof can be provided. This page will be updated as soon as a verifiable recognition is available.", es: "Por honestidad, no mostramos ningún logotipo, sello o etiqueta de acreditación hasta que se haya obtenido oficialmente y pueda aportarse una prueba pública. Esta página se actualizará en cuanto haya un reconocimiento verificable.", it: "Per onestà, non mostriamo alcun logo, sigillo o marchio di accreditamento finché non è stato ottenuto ufficialmente e non può essere fornita una prova pubblica. Questa pagina sarà aggiornata non appena sarà disponibile un riconoscimento verificabile.", pt: "Por honestidade, não apresentamos qualquer logótipo, selo ou rótulo de acreditação até que tenha sido oficialmente obtido e possa ser fornecida uma prova pública. Esta página será atualizada assim que houver um reconhecimento verificável.", de: "Aus Gründen der Ehrlichkeit zeigen wir kein Akkreditierungslogo, -siegel oder -label an, solange es nicht offiziell erlangt wurde und kein öffentlicher Nachweis erbracht werden kann. Diese Seite wird aktualisiert, sobald eine überprüfbare Anerkennung verfügbar ist.", ht: "Pou nou onèt, nou pa montre okenn logo, so oswa etikèt akreditasyon toutotan li poko ofisyèlman jwenn epi yon prèv piblik ka bay. Paj sa a ap mete ajou depi gen yon rekonesans ki ka verifye." },
  "acc.what.title": { fr: "Ce que nous sommes — et ce que nous ne sommes pas", en: "What we are — and what we are not", es: "Lo que somos y lo que no somos", it: "Ciò che siamo — e ciò che non siamo", pt: "O que somos — e o que não somos", de: "Was wir sind — und was nicht", ht: "Sa nou ye — ak sa nou pa ye" },
  "acc.what.body": { fr: "ARCADINS Training Center est un organisme privé de formation et de préparation linguistique. Nous ne sommes pas un organisme gouvernemental, ni un centre officiel d'examen TEF/TCF, ni un cabinet de conseil réglementé en immigration. Nos attestations certifient la complétion de nos propres formations ; elles ne remplacent pas un diplôme officiel ni un résultat d'examen officiel.", en: "ARCADINS Training Center is a private training and language-preparation organization. We are not a government body, an official TEF/TCF exam centre, or a regulated immigration advisory firm. Our certificates attest to the completion of our own courses; they do not replace an official diploma or an official exam result.", es: "ARCADINS Training Center es una organización privada de formación y preparación lingüística. No somos un organismo gubernamental, ni un centro oficial de examen TEF/TCF, ni una firma regulada de asesoría en inmigración. Nuestros certificados acreditan la finalización de nuestros propios cursos; no sustituyen a un diploma oficial ni a un resultado de examen oficial.", it: "ARCADINS Training Center è un'organizzazione privata di formazione e preparazione linguistica. Non siamo un ente governativo, né un centro d'esame ufficiale TEF/TCF, né uno studio di consulenza regolamentata sull'immigrazione. I nostri attestati certificano il completamento dei nostri corsi; non sostituiscono un diploma ufficiale né un risultato d'esame ufficiale.", pt: "O ARCADINS Training Center é uma organização privada de formação e preparação linguística. Não somos um organismo governamental, nem um centro oficial de exame TEF/TCF, nem uma firma regulamentada de aconselhamento em imigração. As nossas atestações certificam a conclusão dos nossos próprios cursos; não substituem um diploma oficial nem um resultado de exame oficial.", de: "ARCADINS Training Center ist eine private Bildungs- und Sprachvorbereitungsorganisation. Wir sind keine Regierungsbehörde, kein offizielles TEF/TCF-Prüfungszentrum und keine regulierte Einwanderungsberatung. Unsere Bescheinigungen bestätigen den Abschluss unserer eigenen Kurse; sie ersetzen weder ein offizielles Diplom noch ein offizielles Prüfungsergebnis.", ht: "ARCADINS Training Center se yon òganizasyon prive fòmasyon ak preparasyon lang. Nou pa yon òganis gouvènmantal, ni yon sant ofisyèl egzamen TEF/TCF, ni yon kabinè konsèy reglemante nan imigrasyon. Atestasyon nou yo sètifye ke ou konplete pwòp fòmasyon nou yo; yo pa ranplase yon diplòm ofisyèl ni yon rezilta egzamen ofisyèl." },
  "acc.nav": { fr: "Accréditations", en: "Accreditations", es: "Acreditaciones", it: "Accreditamenti", pt: "Acreditações", de: "Akkreditierungen", ht: "Akreditasyon" },
  "nav.temoignages": { fr: "Témoignages", en: "Reviews", es: "Testimonios", it: "Testimonianze", pt: "Depoimentos", de: "Erfahrungen", ht: "Temwayaj" },
  "nav.contact": { fr: "Contact", en: "Contact", es: "Contacto", it: "Contatto", pt: "Contato", de: "Kontakt", ht: "Kontak" },
  "nav.cta": { fr: "S'inscrire", en: "Enroll Now", es: "Inscribirse", it: "Iscriviti", pt: "Inscrever-se", de: "Einschreiben", ht: "Enskri" },
  "nav.dashboard": { fr: "Mon tableau de bord", en: "My Dashboard", es: "Mi panel", it: "La mia dashboard", pt: "Meu painel", de: "Mein Dashboard", ht: "Tablo bò mwen" },
  "nav.logout": { fr: "Déconnexion", en: "Log out", es: "Cerrar sesión", it: "Disconnetti", pt: "Sair", de: "Abmelden", ht: "Dekonekte" },

  // Hero
  "hero.badge": { fr: "Formation & préparation TEF/TCF · 7 langues", en: "Training & TEF/TCF preparation · 7 languages", es: "Formación y preparación TEF/TCF · 7 idiomas", it: "Formazione e preparazione TEF/TCF · 7 lingue", pt: "Formação e preparação TEF/TCF · 7 idiomas", de: "Ausbildung & TEF/TCF-Vorbereitung · 7 Sprachen", ht: "Fòmasyon & preparasyon TEF/TCF · 7 lang" },
  "hero.title1": { fr: "Formez-vous, intégrez-vous", en: "Train, integrate yourself", es: "Fórmate, intégrate", it: "Formati, intégrati", pt: "Forme-se, integre-se", de: "Bilden Sie sich weiter", ht: "Fòme w, entegre w" },
  "hero.title2": { fr: "et bâtissez votre", en: "and build your", es: "y construye tu", it: "e costruisci il tuo", pt: "e construa seu", de: "und bauen Sie Ihre", ht: "epi bati" },
  "hero.title3": { fr: "avenir au Canada", en: "future in Canada", es: "futuro en Canadá", it: "futuro in Canada", pt: "futuro no Canadá", de: "Zukunft in Kanada", ht: "avni ou nan Kanada" },
  "hero.desc": { fr: "ARCADINS Training Center accompagne les nouveaux arrivants, les étudiants et les professionnels vers la formation, l'intégration, l'emploi et la réussite au Canada.", en: "ARCADINS Training Center supports newcomers, students and professionals toward training, integration, employment and success in Canada.", es: "ARCADINS Training Center acompaña a los recién llegados, estudiantes y profesionales hacia la formación, integración, empleo y éxito en Canadá.", it: "ARCADINS Training Center accompagna i nuovi arrivati, gli studenti e i professionisti verso la formazione, l'integrazione e il successo in Canada.", pt: "ARCADINS Training Center apoia recém-chegados, estudantes e profissionais rumo à formação, integração, emprego e sucesso no Canadá.", de: "ARCADINS Training Center begleitet Neuzuwanderer, Studierende und Fachkräfte zu Ausbildung, Integration, Beschäftigung und Erfolg in Kanada.", ht: "ARCADINS Training Center akonpaye nouvo vini yo, etidyan ak pwofesyonèl yo nan fòmasyon, entegrasyon, travay ak reyisit nan Kanada." },
  "hero.cta1": { fr: "Commencer ma formation", en: "Start my training", es: "Iniciar mi formación", it: "Inizia la formazione", pt: "Começar formação", de: "Ausbildung starten", ht: "Kòmanse fòmasyon mwen" },
  "hero.cta2": { fr: "Découvrir nos programmes →", en: "Discover our programs →", es: "Descubrir programas →", it: "Scopri i programmi →", pt: "Descobrir programas →", de: "Programme entdecken →", ht: "Dekouvri pwogram nou yo →" },

  // Stats
  "stat.apprenants": { fr: "Apprenants formés", en: "Students trained", es: "Estudiantes", it: "Studenti", pt: "Estudantes", de: "Ausgebildete", ht: "Etidyan" },
  "stat.reussite": { fr: "Réussite TEF/TCF", en: "TEF/TCF success", es: "Tasa de éxito", it: "Successo TEF", pt: "Taxa aprovação", de: "Erfolgsquote", ht: "To siksè" },
  "stat.pays": { fr: "Pays couverts", en: "Countries", es: "Países", it: "Paesi", pt: "Países", de: "Länder", ht: "Peyi" },
  "stat.programmes": { fr: "Programmes certifiés", en: "Programs", es: "Programas", it: "Programmi", pt: "Programas", de: "Programme", ht: "Pwogram" },

  // Services
  "services.label": { fr: "Nos Services Phares", en: "Our Key Services", es: "Nuestros Servicios", it: "I Nostri Servizi", pt: "Nossos Serviços", de: "Unsere Dienste", ht: "Sèvis Nou Yo" },
  "services.title1": { fr: "Tout ce dont vous avez besoin,", en: "Everything you need,", es: "Todo lo que necesitas,", it: "Tutto ciò di cui hai bisogno,", pt: "Tudo o que você precisa,", de: "Alles, was Sie brauchen,", ht: "Tout sa ou bezwen," },
  "services.title2": { fr: "en un seul endroit", en: "in one place", es: "en un solo lugar", it: "in un unico posto", pt: "em um só lugar", de: "an einem Ort", ht: "nan yon sèl kote" },

  // CTA
  "cta.start_tef": { fr: "Commencer le TEF / TCF", en: "Start TEF / TCF", es: "Iniciar TEF / TCF", it: "Inizia TEF / TCF", pt: "Começar TEF / TCF", de: "TEF / TCF starten", ht: "Kòmanse TEF / TCF" },
  "cta.see_formations": { fr: "Voir les formations →", en: "See programs →", es: "Ver programas →", it: "Vedi programmi →", pt: "Ver programas →", de: "Programme sehen →", ht: "Wè pwogram yo →" },
  "cta.ready": { fr: "Prêt à commencer votre parcours vers", en: "Ready to start your journey to", es: "Listo para comenzar tu camino hacia", it: "Pronto a iniziare il tuo percorso verso", pt: "Pronto para começar sua jornada para", de: "Bereit, Ihre Reise nach", ht: "Pare pou kòmanse vwayaj ou nan" },
  "cta.canada": { fr: "le Canada", en: "Canada", es: "Canadá", it: "il Canada", pt: "o Canadá", de: "Kanada zu beginnen", ht: "Kanada" },
  "cta.join": { fr: "Rejoignez une communauté d'apprenants qui préparent leur avenir au Canada avec ARCADINS.", en: "Join a community of learners preparing their future in Canada with ARCADINS.", es: "Únase a una comunidad de estudiantes que preparan su futuro en Canadá con ARCADINS.", it: "Unisciti a una comunità di studenti che preparano il loro futuro in Canada con ARCADINS.", pt: "Junte-se a uma comunidade de alunos que preparam o seu futuro no Canadá com a ARCADINS.", de: "Werden Sie Teil einer Gemeinschaft von Lernenden, die ihre Zukunft in Kanada mit ARCADINS vorbereiten.", ht: "Rejwenn yon kominote apranti k ap prepare avni yo nan Kanada ak ARCADINS." },

  // Video section
  "video.label": { fr: "Formations & Immigration · Ressources vidéo", en: "Training & Immigration · Video Resources", es: "Formación & Inmigración · Recursos de video", it: "Formazione & Immigrazione · Risorse video", pt: "Formação & Imigração · Recursos de vídeo", de: "Ausbildung & Einwanderung · Videoressourcen", ht: "Fòmasyon & Imigrasyon · Resous videyo" },
  "video.title1": { fr: "Apprenez, préparez-vous,", en: "Learn, prepare yourself,", es: "Aprende, prepárate,", it: "Impara, preparati,", pt: "Aprenda, prepare-se,", de: "Lernen, bereiten Sie sich vor,", ht: "Aprann, prepare w," },
  "video.title2": { fr: "réussissez au Canada", en: "succeed in Canada", es: "triunfa en Canadá", it: "riuscite in Canada", pt: "tenha sucesso no Canadá", de: "Erfolg in Kanada", ht: "reyisi nan Kanada" },
  "video.desc": { fr: "Nos ressources vidéo couvrent les tests TEF/TCF, les démarches d'immigration et les formations professionnelles.", en: "Our video resources cover TEF/TCF tests, immigration procedures and professional training.", es: "Nuestros recursos de video cubren los exámenes TEF/TCF, los trámites de inmigración y la formación profesional.", it: "Le nostre risorse video coprono i test TEF/TCF, le procedure di immigrazione e la formazione professionale.", pt: "Nossos recursos de vídeo cobrem os testes TEF/TCF, os procedimentos de imigração e a formação profissional.", de: "Unsere Videoressourcen decken TEF/TCF-Tests, Einwanderungsverfahren und Berufsausbildung ab.", ht: "Resous videyo nou yo kouvri tès TEF/TCF, pwosedi imigrasyon ak fòmasyon pwofesyonèl." },

  // Stats bar
  "stats.apprenants": { fr: "Apprenants", en: "Students", es: "Estudiantes", it: "Studenti", pt: "Estudantes", de: "Studierende", ht: "Etidyan" },
  "stats.pays": { fr: "Pays", en: "Countries", es: "Países", it: "Paesi", pt: "Países", de: "Länder", ht: "Peyi" },
  "stats.reussite": { fr: "Réussite TEF", en: "TEF Success", es: "Éxito TEF", it: "Successo TEF", pt: "Aprovação TEF", de: "TEF Erfolg", ht: "Siksè TEF" },
  "stats.langues": { fr: "Langues", en: "Languages", es: "Idiomas", it: "Lingue", pt: "Idiomas", de: "Sprachen", ht: "Lang" },
  "stats.formations": { fr: "Formations", en: "Programs", es: "Formaciones", it: "Corsi", pt: "Formações", de: "Programme", ht: "Fòmasyon" },
  "stats.modules": { fr: "Modules", en: "Modules", es: "Módulos", it: "Moduli", pt: "Módulos", de: "Module", ht: "Modil" },
  "stats.competences": { fr: "Compétences", en: "Skills", es: "Competencias", it: "Competenze", pt: "Competências", de: "Kompetenzen", ht: "Konpetans" },
  "stats.programmes": { fr: "Programmes", en: "Programs", es: "Programas", it: "Programmi", pt: "Programas", de: "Programme", ht: "Pwogram" },
  "stats.reconnu": { fr: "Reconnu par :", en: "Recognized by:", es: "Reconocido por:", it: "Riconosciuto da:", pt: "Reconhecido por:", de: "Anerkannt von:", ht: "Rekonèt pa :" },

  // Services cards
  "svc.tests.cat": { fr: "Préparation aux tests", en: "Test Preparation", es: "Preparación de tests", it: "Preparazione ai test", pt: "Preparação para testes", de: "Testvorbereitung", ht: "Preparasyon tès" },
  "svc.tests.name": { fr: "TEF / TCF Canada", en: "TEF / TCF Canada", es: "TEF / TCF Canadá", it: "TEF / TCF Canada", pt: "TEF / TCF Canadá", de: "TEF / TCF Kanada", ht: "TEF / TCF Kanada" },
  "svc.tests.desc": { fr: "Préparation complète aux tests de langue officielle pour l'immigration canadienne.", en: "Complete preparation for official language tests for Canadian immigration.", es: "Preparación completa para los tests de idioma oficial para la inmigración canadiense.", it: "Preparazione completa ai test di lingua ufficiale per l'immigrazione canadese.", pt: "Preparação completa para os testes de idioma oficial para a imigração canadense.", de: "Vollständige Vorbereitung auf offizielle Sprachtests für die kanadische Einwanderung.", ht: "Preparasyon konplè pou tès lang ofisyèl pou imigrasyon kanadyen." },
  "svc.formations.cat": { fr: "Formations professionnelles", en: "Professional Programs", es: "Programas profesionales", it: "Programmi professionali", pt: "Programas profissionais", de: "Berufsprogramme", ht: "Fòmasyon pwofesyonèl" },
  "svc.formations.name": { fr: "Formations professionnelles", en: "Professional Training", es: "Formación profesional", it: "Formazione professionale", pt: "Formação profissional", de: "Berufsausbildung", ht: "Fòmasyon pwofesyonèl" },
  "svc.formations.desc": { fr: "Marketing, Finance, Tech, RH, Tourisme, Français des affaires et plus — avec attestation de complétion.", en: "Marketing, Finance, Tech, HR, Tourism, Business French and more — with a certificate of completion.", es: "Marketing, Finanzas, Tech, RR. HH., Turismo, Francés de negocios y más — con certificado de finalización.", it: "Marketing, Finanza, Tech, RU, Turismo, Francese degli affari e altro — con attestato di completamento.", pt: "Marketing, Finanças, Tech, RH, Turismo, Francês de negócios e mais — com certificado de conclusão.", de: "Marketing, Finanzen, Tech, HR, Tourismus, Geschäftsfranzösisch und mehr — mit Abschlussbescheinigung.", ht: "Maketing, Finans, Tech, RH, Touris, Fransè zafè ak plis — ak yon atestasyon konplete." },
  "svc.examens.cat": { fr: "100% en ligne", en: "100% Online", es: "100% en línea", it: "100% Online", pt: "100% Online", de: "100% Online", ht: "100% sou entènèt" },
  "svc.examens.name": { fr: "Examens & Certificats", en: "Exams & Certificates", es: "Exámenes & Certificados", it: "Esami & Certificati", pt: "Exames & Certificados", de: "Prüfungen & Zertifikate", ht: "Egzamen & Sètifika" },
  "svc.examens.desc": { fr: "Passez votre examen et recevez votre certificat numérique instantanément.", en: "Take your exam and receive your digital certificate instantly.", es: "Realice su examen y reciba su certificado digital al instante.", it: "Sostenete il vostro esame e ricevete il vostro certificato digitale istantaneamente.", pt: "Faça seu exame e receba seu certificado digital instantaneamente.", de: "Legen Sie Ihre Prüfung ab und erhalten Sie Ihr digitales Zertifikat sofort.", ht: "Pase egzamen ou epi resevwa sètifika dijital ou imedyatman." },
  "svc.immigration.cat": { fr: "Information", en: "Information", es: "Información", it: "Informazione", pt: "Informação", de: "Information", ht: "Enfòmasyon" },
  "svc.immigration.name": { fr: "Programmes d'immigration", en: "Immigration Programs", es: "Programas de inmigración", it: "Programmi di immigrazione", pt: "Programas de imigração", de: "Einwanderungsprogramme", ht: "Pwogram imigrasyon" },
  "svc.immigration.desc": { fr: "Information générale sur les programmes d'immigration au Canada. Ne constitue pas un avis juridique.", en: "General information on immigration programs in Canada. Not legal advice.", es: "Información general sobre los programas de inmigración en Canadá. No constituye asesoría jurídica.", it: "Informazioni generali sui programmi di immigrazione in Canada. Non costituisce consulenza legale.", pt: "Informação geral sobre os programas de imigração no Canadá. Não constitui aconselhamento jurídico.", de: "Allgemeine Informationen zu Einwanderungsprogrammen in Kanada. Keine Rechtsberatung.", ht: "Enfòmasyon jeneral sou pwogram imigrasyon nan Kanada. Se pa yon konsèy jiridik." },

  // Footer
  "footer.desc": { fr: "Plateforme de formation professionnelle et de préparation aux tests de français (TEF/TCF), pensée pour les nouveaux arrivants et professionnels visant le Canada. Disponible en 7 langues.", en: "Professional training and French test (TEF/TCF) preparation platform, designed for newcomers and professionals aiming for Canada. Available in 7 languages.", es: "Plataforma de formación profesional y preparación para exámenes de francés (TEF/TCF), pensada para recién llegados y profesionales que aspiran a Canadá. Disponible en 7 idiomas.", it: "Piattaforma di formazione professionale e preparazione ai test di francese (TEF/TCF), pensata per i nuovi arrivati e i professionisti che puntano al Canada. Disponibile in 7 lingue.", pt: "Plataforma de formação profissional e preparação para testes de francês (TEF/TCF), pensada para recém-chegados e profissionais que visam o Canadá. Disponível em 7 idiomas.", de: "Plattform für Berufsausbildung und Französischtest-Vorbereitung (TEF/TCF), konzipiert für Neuzuwanderer und Fachkräfte mit Ziel Kanada. In 7 Sprachen verfügbar.", ht: "Platfòm fòmasyon pwofesyonèl ak preparasyon tès fransè (TEF/TCF), fèt pou nouvo arivan ak pwofesyonèl k ap vize Kanada. Disponib nan 7 lang." },
  "footer.formations": { fr: "Formations", en: "Programs", es: "Programas", it: "Programmi", pt: "Programas", de: "Programme", ht: "Pwogram" },
  "footer.services": { fr: "Services", en: "Services", es: "Servicios", it: "Servizi", pt: "Serviços", de: "Dienste", ht: "Sèvis" },
  "footer.contact": { fr: "Contact", en: "Contact", es: "Contacto", it: "Contatto", pt: "Contato", de: "Kontakt", ht: "Kontak" },
  "footer.copyright": { fr: "© 2025 ARCADINS Training Center — Tous droits réservés", en: "© 2025 ARCADINS Training Center — All rights reserved", es: "© 2025 ARCADINS Training Center — Todos los derechos reservados", it: "© 2025 ARCADINS Training Center — Tutti i diritti riservati", pt: "© 2025 ARCADINS Training Center — Todos os direitos reservados", de: "© 2025 ARCADINS Training Center — Alle Rechte vorbehalten", ht: "© 2025 ARCADINS Training Center — Tout dwa rezève" },
  "footer.whatsapp": { fr: "WhatsApp Business", en: "WhatsApp Business", es: "WhatsApp Business", it: "WhatsApp Business", pt: "WhatsApp Business", de: "WhatsApp Business", ht: "WhatsApp Business" },
  "footer.privacy": { fr: "Politique de confidentialité", en: "Privacy Policy", es: "Política de privacidad", it: "Informativa sulla privacy", pt: "Política de privacidade", de: "Datenschutzrichtlinie", ht: "Politik konfidansyalite" },
  "footer.terms": { fr: "Conditions d'utilisation", en: "Terms of Use", es: "Términos de uso", it: "Condizioni d'uso", pt: "Termos de uso", de: "Nutzungsbedingungen", ht: "Kondisyon itilizasyon" },
  "footer.seal1": { fr: "🍁 Contenu adapté au Canada", en: "🍁 Canada-focused content", es: "🍁 Contenido adaptado a Canadá", it: "🍁 Contenuti adattati al Canada", pt: "🍁 Conteúdo adaptado ao Canadá", de: "🍁 Auf Kanada ausgerichtete Inhalte", ht: "🍁 Kontni adapte pou Kanada" },
  "footer.seal2": { fr: "🎓 Préparation TEF / TCF", en: "🎓 TEF / TCF preparation", es: "🎓 Preparación TEF / TCF", it: "🎓 Preparazione TEF / TCF", pt: "🎓 Preparação TEF / TCF", de: "🎓 TEF / TCF-Vorbereitung", ht: "🎓 Preparasyon TEF / TCF" },
  "footer.seal3": { fr: "🌐 7 langues", en: "🌐 7 languages", es: "🌐 7 idiomas", it: "🌐 7 lingue", pt: "🌐 7 idiomas", de: "🌐 7 Sprachen", ht: "🌐 7 lang" },

  // Footer links
  "fl.leadership": { fr: "Leadership & Gestion", en: "Leadership & Management", es: "Liderazgo & Gestión", it: "Leadership & Gestione", pt: "Liderança & Gestão", de: "Führung & Management", ht: "Lidèchip & Jesyon" },
  "fl.epe": { fr: "Éducatrice EPE", en: "Early Childhood Educator", es: "Educadora EPE", it: "Educatrice EPE", pt: "Educadora EPE", de: "Frühkindliche Erzieherin", ht: "Edikatris EPE" },
  "fl.pab": { fr: "PAB Québec", en: "PAB Quebec", es: "PAB Quebec", it: "PAB Quebec", pt: "PAB Quebec", de: "PAB Quebec", ht: "PAB Quebec" },
  "fl.informatique": { fr: "Informatique & IA", en: "IT & AI", es: "Informática & IA", it: "Informatica & IA", pt: "Informática & IA", de: "Informatik & KI", ht: "Enfòmatik & IA" },
  "fl.dette": { fr: "Famille Sans Dette", en: "Debt-Free Family", es: "Familia Sin Deudas", it: "Famiglia Senza Debiti", pt: "Família Sem Dívidas", de: "Familie ohne Schulden", ht: "Fanmi San Dèt" },
  "fl.examens": { fr: "Examens en ligne", en: "Online Exams", es: "Exámenes en línea", it: "Esami online", pt: "Exames online", de: "Online-Prüfungen", ht: "Egzamen sou entènèt" },
  "fl.certificats": { fr: "Certificats numériques", en: "Digital Certificates", es: "Certificados digitales", it: "Certificati digitali", pt: "Certificados digitais", de: "Digitale Zertifikate", ht: "Sètifika dijital" },
  "fl.ircc": { fr: "Info immigration", en: "Immigration Info", es: "Info inmigración", it: "Info immigrazione", pt: "Info imigração", de: "Einwanderungsinfo", ht: "Enfo imigrasyon" },
  "fl.emploi": { fr: "Préparation à l'emploi", en: "Job Preparation", es: "Preparación al empleo", it: "Preparazione al lavoro", pt: "Preparação para o emprego", de: "Berufsvorbereitung", ht: "Preparasyon travay" },
  "fl.tarifs": { fr: "Nos tarifs", en: "Our Pricing", es: "Nuestros precios", it: "I nostri prezzi", pt: "Nossos preços", de: "Unsere Preise", ht: "Pri nou yo" },
  "fl.contacter": { fr: "Nous contacter", en: "Contact Us", es: "Contáctenos", it: "Contattaci", pt: "Fale conosco", de: "Kontaktieren Sie uns", ht: "Kontakte nou" },

  // ═══ TEF PAGE ═══
  "tef.label": { fr: "Préparation TEF / TCF · Immigration Canada", en: "TEF / TCF Preparation · Immigration Canada", es: "Preparación TEF / TCF · Inmigración Canadá", it: "Preparazione TEF / TCF · Immigrazione Canada", pt: "Preparação TEF / TCF · Imigração Canadá", de: "TEF / TCF-Vorbereitung · Einwanderung Kanada", ht: "Preparasyon TEF / TCF · Imigrasyon Kanada" },
  "tef.title1": { fr: "Préparez votre", en: "Prepare your", es: "Prepara tu", it: "Prepara il tuo", pt: "Prepare seu", de: "Bereiten Sie Ihren", ht: "Prepare" },
  "tef.title2": { fr: "Test de Français", en: "French Test", es: "Test de Francés", it: "Test di Francese", pt: "Teste de Francês", de: "Französischtest vor", ht: "Tès Fransè ou" },
  "tef.title3": { fr: "pour immigrer au Canada", en: "to immigrate to Canada", es: "para inmigrar a Canadá", it: "per immigrare in Canada", pt: "para imigrar ao Canadá", de: "für die Einwanderung nach Kanada", ht: "pou imigre nan Kanada" },
  "tef.desc": { fr: "Les tests TEF Canada et TCF Canada sont obligatoires pour la résidence permanente, la citoyenneté et les programmes d'immigration provinciaux. Notre taux de réussite est de", en: "TEF Canada and TCF Canada tests are mandatory for permanent residence, citizenship and provincial immigration programs. Our success rate is", es: "Los tests TEF Canadá y TCF Canadá son obligatorios para la residencia permanente, la ciudadanía y los programas de inmigración provinciales. Nuestra tasa de éxito es del", it: "I test TEF Canada e TCF Canada sono obbligatori per la residenza permanente, la cittadinanza e i programmi di immigrazione provinciali. Il nostro tasso di successo è del", pt: "Os testes TEF Canadá e TCF Canadá são obrigatórios para residência permanente, cidadania e programas de imigração provinciais. Nossa taxa de aprovação é de", de: "TEF Kanada und TCF Kanada Tests sind obligatorisch für die dauerhafte Aufenthaltsgenehmigung, Staatsbürgerschaft und provinzielle Einwanderungsprogramme. Unsere Erfolgsquote beträgt", ht: "Tès TEF Kanada ak TCF Kanada obligatwa pou rezidans pèmanan, sitwayènte ak pwogram imigrasyon pwovensyal. To siksè nou se" },
  "tef.panel.title": { fr: "Notre Préparation Complète", en: "Our Complete Preparation", es: "Nuestra Preparación Completa", it: "La Nostra Preparazione Completa", pt: "Nossa Preparação Completa", de: "Unsere Komplette Vorbereitung", ht: "Preparasyon Konplè Nou" },
  "tef.panel.sub": { fr: "Méthode de préparation structurée ARCADINS", en: "Structured ARCADINS preparation method", es: "Método de preparación estructurado ARCADINS", it: "Metodo di preparazione strutturato ARCADINS", pt: "Método de preparação estruturado ARCADINS", de: "Strukturierte ARCADINS-Vorbereitungsmethode", ht: "Metòd preparasyon estriktire ARCADINS" },
  "tef.panel.cta": { fr: "Commencer ma préparation TEF →", en: "Start my TEF preparation →", es: "Iniciar mi preparación TEF →", it: "Inizia la preparazione TEF →", pt: "Começar preparação TEF →", de: "TEF-Vorbereitung starten →", ht: "Kòmanse preparasyon TEF mwen →" },
  "tef.panel.how": { fr: "Comment se déroule l'examen en ligne ?", en: "How does the online exam work?", es: "¿Cómo funciona el examen en línea?", it: "Come funziona l'esame online?", pt: "Como funciona o exame online?", de: "Wie funktioniert die Online-Prüfung?", ht: "Kijan egzamen sou entènèt la fèt?" },
  "tef.ck1": { fr: "Cours en direct avec formateurs bilingues expérimentés", en: "Live courses with experienced bilingual instructors", es: "Clases en vivo con formadores bilingües con experiencia", it: "Corsi dal vivo con formatori bilingui esperti", pt: "Aulas ao vivo com formadores bilingues experientes", de: "Live-Kurse mit erfahrenen zweisprachigen Ausbildern", ht: "Kou an dirèk ak fòmatè bileng ki gen eksperyans" },
  "tef.ck2": { fr: "Simulations complètes des 4 compétences (CO / CE / PO / PE)", en: "Full simulations of all 4 skills (LC / RC / SO / WE)", es: "Simulaciones completas de las 4 competencias (CO / CE / PO / PE)", it: "Simulazioni complete delle 4 competenze (CO / CE / PO / PE)", pt: "Simulações completas das 4 competências (CO / CE / PO / PE)", de: "Vollständige Simulationen aller 4 Kompetenzen (HV / LV / MA / SA)", ht: "Similasyon konplè 4 konpetans yo (CO / CE / PO / PE)" },
  "tef.ck3": { fr: "Bibliothèque de 2 000+ exercices niveau A1 à C2", en: "Library of 2,000+ exercises from A1 to C2", es: "Biblioteca de 2.000+ ejercicios nivel A1 a C2", it: "Libreria di 2.000+ esercizi livello A1 a C2", pt: "Biblioteca de 2.000+ exercícios nível A1 a C2", de: "Bibliothek mit 2.000+ Übungen von A1 bis C2", ht: "Bibliyotèk 2 000+ egzèsis nivo A1 rive C2" },
  "tef.ck4": { fr: "Correction personnalisée des productions écrites sous 48h", en: "Personalized correction of written productions within 48h", es: "Corrección personalizada de producciones escritas en 48h", it: "Correzione personalizzata delle produzioni scritte entro 48h", pt: "Correção personalizada das produções escritas em 48h", de: "Personalisierte Korrektur schriftlicher Produktionen innerhalb von 48h", ht: "Koreksyon pèsonalize pwoduksyon ekri nan 48è" },
  "tef.ck5": { fr: "Coaching oral individuel — accent, fluidité, vocabulaire", en: "Individual oral coaching — accent, fluency, vocabulary", es: "Coaching oral individual — acento, fluidez, vocabulario", it: "Coaching orale individuale — accento, fluidità, vocabolario", pt: "Coaching oral individual — sotaque, fluência, vocabulário", de: "Individuelles mündliches Coaching — Akzent, Flüssigkeit, Wortschatz", ht: "Coaching oral endividyèl — aksan, fliwidite, vokabilè" },
  "tef.ck6": { fr: "Suivi IA de progression par compétence", en: "AI-powered progress tracking by skill", es: "Seguimiento IA de progreso por competencia", it: "Monitoraggio IA dei progressi per competenza", pt: "Acompanhamento IA de progresso por competência", de: "KI-gestütztes Fortschrittstracking nach Kompetenz", ht: "Swivi IA pwogresyon pa konpetans" },
  "tef.ck7": { fr: "Accompagnement personnalisé jusqu'à votre passage du test", en: "Personalized support up to your test day", es: "Acompañamiento personalizado hasta el día de su examen", it: "Accompagnamento personalizzato fino al giorno del test", pt: "Acompanhamento personalizado até o dia do seu teste", de: "Persönliche Begleitung bis zu Ihrem Prüfungstag", ht: "Akonpayeman pèsonalize jiska jou tès ou" },
  "tef.step1": { fr: "Connexion sécurisée", en: "Secure login", es: "Conexión segura", it: "Connessione sicura", pt: "Conexão segura", de: "Sichere Anmeldung", ht: "Koneksyon sekirize" },
  "tef.step2": { fr: "Vérification identité Proctor IA", en: "AI Proctor identity verification", es: "Verificación de identidad Proctor IA", it: "Verifica identità Proctor IA", pt: "Verificação de identidade Proctor IA", de: "KI-Proctor Identitätsprüfung", ht: "Verifikasyon idantite Proctor IA" },
  "tef.step3": { fr: "Passage des 4 modules", en: "Complete 4 guided modules", es: "Realización de los 4 módulos", it: "Completamento dei 4 moduli", pt: "Realização dos 4 módulos", de: "Durchlauf der 4 Module", ht: "Pasaj 4 modil yo" },
  "tef.step4": { fr: "Résultats & certificat", en: "Results & certificate", es: "Resultados & certificado", it: "Risultati & certificato", pt: "Resultados & certificado", de: "Ergebnisse & Zertifikat", ht: "Rezilta & sètifika" },

  // ═══ FORMATIONS PAGE ═══
  "form.label": { fr: "Formations professionnelles · 7 langues", en: "Professional Programs · 7 languages", es: "Programas profesionales · 7 idiomas", it: "Programmi professionali · 7 lingue", pt: "Programas profissionais · 7 idiomas", de: "Berufsprogramme · 7 Sprachen", ht: "Fòmasyon pwofesyonèl · 7 lang" },
  "form.title1": { fr: "Formations", en: "Training", es: "Formación", it: "Formazione", pt: "Formação", de: "Ausbildung", ht: "Fòmasyon" },
  "form.title2": { fr: "professionnelles", en: "professional", es: "profesionales", it: "professionali", pt: "profissionais", de: "beruflich", ht: "pwofesyonèl" },
  "form.title3": { fr: "adaptées au marché canadien, en 7 langues", en: "tailored to the Canadian market, in 7 languages", es: "adaptadas al mercado canadiense, en 7 idiomas", it: "su misura per il mercato canadese, in 7 lingue", pt: "adaptadas ao mercado canadiano, em 7 línguas", de: "auf den kanadischen Markt zugeschnitten, in 7 Sprachen", ht: "adapte pou mache kanadyen an, nan 7 lang" },
  "form.all": { fr: "Tous", en: "All", es: "Todos", it: "Tutti", pt: "Todos", de: "Alle", ht: "Tout" },
  "form.see": { fr: "Voir →", en: "View →", es: "Ver →", it: "Vedi →", pt: "Ver →", de: "Ansehen →", ht: "Wè →" },

  // ═══ EXAMENS PAGE ═══
  "exam.label": { fr: "Plateforme LMS Propriétaire", en: "Proprietary LMS Platform", es: "Plataforma LMS Propietaria", it: "Piattaforma LMS Proprietaria", pt: "Plataforma LMS Proprietária", de: "Eigene LMS-Plattform", ht: "Platfòm LMS Pwopriyetè" },
  "exam.title1": { fr: "Passez vos examens en ligne,", en: "Take your exams online,", es: "Realice sus exámenes en línea,", it: "Sostenete i vostri esami online,", pt: "Faça seus exames online,", de: "Legen Sie Ihre Prüfungen online ab,", ht: "Pase egzamen ou sou entènèt," },
  "exam.title2": { fr: "recevez votre", en: "receive your", es: "reciba su", it: "ricevete il vostro", pt: "receba seu", de: "erhalten Sie Ihr", ht: "resevwa" },
  "exam.title3": { fr: "certificat immédiatement", en: "certificate immediately", es: "certificado inmediatamente", it: "certificato immediatamente", pt: "certificado imediatamente", de: "Zertifikat sofort", ht: "sètifika ou imedyatman" },
  "exam.desc": { fr: "Plateforme sécurisée avec proctoring IA, anti-triche, résultats instantanés et certificats numériques avec QR code de vérification.", en: "Secure platform with AI proctoring, anti-cheat, instant results and digital certificates with QR verification code.", es: "Plataforma segura con supervisión IA, anti-trampas, resultados instantáneos y certificados digitales con código QR de verificación.", it: "Piattaforma sicura con proctoring IA, anti-frode, risultati istantanei e certificati digitali con codice QR di verifica.", pt: "Plataforma segura com proctoring IA, anti-fraude, resultados instantâneos e certificados digitais com código QR de verificação.", de: "Sichere Plattform mit KI-Proctoring, Anti-Betrug, sofortige Ergebnisse und digitale Zertifikate mit QR-Verifizierungscode.", ht: "Platfòm sekirize ak proctoring IA, anti-trich, rezilta imedya ak sètifika dijital ak kòd QR verifikasyon." },
  "exam.score": { fr: "Score en temps réel", en: "Real-time Score", es: "Puntuación en tiempo real", it: "Punteggio in tempo reale", pt: "Pontuação em tempo real", de: "Echtzeit-Ergebnis", ht: "Nòt an tan reyèl" },
  "exam.level": { fr: "Niveau", en: "Level", es: "Nivel", it: "Livello", pt: "Nível", de: "Stufe", ht: "Nivo" },
  "exam.co": { fr: "Compréhension Orale", en: "Listening Comprehension", es: "Comprensión Oral", it: "Comprensione Orale", pt: "Compreensão Oral", de: "Hörverstehen", ht: "Konpreyansyon Oral" },
  "exam.ee": { fr: "Expression Écrite", en: "Written Expression", es: "Expresión Escrita", it: "Espressione Scritta", pt: "Expressão Escrita", de: "Schriftlicher Ausdruck", ht: "Ekspresyon Ekri" },
  "exam.eo": { fr: "Expression Orale", en: "Oral Expression", es: "Expresión Oral", it: "Espressione Orale", pt: "Expressão Oral", de: "Mündlicher Ausdruck", ht: "Ekspresyon Oral" },
  "exam.inprogress": { fr: "En cours…", en: "In progress…", es: "En curso…", it: "In corso…", pt: "Em andamento…", de: "In Bearbeitung…", ht: "Ap fèt…" },
  "exam.cert": { fr: "Certificat Numérique", en: "Digital Certificate", es: "Certificado Digital", it: "Certificato Digitale", pt: "Certificado Digital", de: "Digitales Zertifikat", ht: "Sètifika Dijital" },
  "exam.certdesc": { fr: "QR code de vérification du certificat", en: "Certificate verification QR code", es: "Código QR de verificación del certificado", it: "Codice QR di verifica del certificato", pt: "Código QR de verificação do certificado", de: "QR-Code zur Zertifikatsprüfung", ht: "Kòd QR verifikasyon sètifika a" },
  "exam.security": { fr: "Sécurité", en: "Security", es: "Seguridad", it: "Sicurezza", pt: "Segurança", de: "Sicherheit", ht: "Sekirite" },
  "exam.proctor": { fr: "Session Proctor IA active", en: "AI Proctor session active", es: "Sesión Proctor IA activa", it: "Sessione Proctor IA attiva", pt: "Sessão Proctor IA ativa", de: "KI-Proctor Sitzung aktiv", ht: "Sesyon Proctor IA aktif" },
  "exam.prev": { fr: "← Précédent", en: "← Previous", es: "← Anterior", it: "← Precedente", pt: "← Anterior", de: "← Zurück", ht: "← Avan" },
  "exam.next": { fr: "Suivant →", en: "Next →", es: "Siguiente →", it: "Successivo →", pt: "Próximo →", de: "Weiter →", ht: "Swivan →" },

  // ═══ IMMIGRATION PAGE ═══
  "imm.label": { fr: "Partenaires & Accompagnement", en: "Partners & Support", es: "Socios & Acompañamiento", it: "Partner & Accompagnamento", pt: "Parceiros & Acompanhamento", de: "Partner & Begleitung", ht: "Patnè & Akonpayeman" },
  "imm.title1": { fr: "Votre chemin vers le", en: "Your path to", es: "Tu camino hacia", it: "Il tuo percorso verso il", pt: "Seu caminho para o", de: "Ihr Weg nach", ht: "Chemen ou nan" },
  "imm.title2": { fr: "Canada", en: "Canada", es: "Canadá", it: "Canada", pt: "Canadá", de: "Kanada", ht: "Kanada" },
  "imm.title3": { fr: "commence ici", en: "starts here", es: "comienza aquí", it: "inizia qui", pt: "começa aqui", de: "beginnt hier", ht: "kòmanse isit" },
  "imm.desc": { fr: "Information générale sur les programmes d'immigration au Canada et préparation linguistique. Ces contenus sont éducatifs et ne constituent pas un avis juridique en immigration.", en: "General information on immigration programs in Canada and language preparation. This content is educational and does not constitute legal immigration advice.", es: "Información general sobre los programas de inmigración en Canadá y preparación lingüística. Estos contenidos son educativos y no constituyen asesoría jurídica en inmigración.", it: "Informazioni generali sui programmi di immigrazione in Canada e preparazione linguistica. Questi contenuti sono educativi e non costituiscono consulenza legale in materia di immigrazione.", pt: "Informação geral sobre os programas de imigração no Canadá e preparação linguística. Estes conteúdos são educativos e não constituem aconselhamento jurídico em imigração.", de: "Allgemeine Informationen zu Einwanderungsprogrammen in Kanada und Sprachvorbereitung. Diese Inhalte sind bildend und stellen keine rechtliche Einwanderungsberatung dar.", ht: "Enfòmasyon jeneral sou pwogram imigrasyon nan Kanada ak preparasyon lengwistik. Kontni sa yo edikatif epi yo pa konstitye yon konsèy jiridik nan imigrasyon." },
  "imm.cta": { fr: "Consultation gratuite →", en: "Free consultation →", es: "Consulta gratuita →", it: "Consulenza gratuita →", pt: "Consulta gratuita →", de: "Kostenlose Beratung →", ht: "Konsiltasyon gratis →" },
  "imm.panel.title": { fr: "Programmes d'immigration ciblés", en: "Targeted immigration programs", es: "Programas de inmigración específicos", it: "Programmi di immigrazione mirati", pt: "Programas de imigração direcionados", de: "Gezielte Einwanderungsprogramme", ht: "Pwogram imigrasyon sible" },
  "imm.s1.title": { fr: "Évaluation du profil d'immigration", en: "Immigration profile assessment", es: "Evaluación del perfil de inmigración", it: "Valutazione del profilo di immigrazione", pt: "Avaliação do perfil de imigração", de: "Bewertung des Einwanderungsprofils", ht: "Evalyasyon pwofil imigrasyon" },
  "imm.s1.desc": { fr: "Test de positionnement linguistique + analyse de votre dossier pour identifier le programme optimal (Express Entry, PEQ, MPNP, etc.).", en: "Language placement test + analysis of your file to identify the optimal program (Express Entry, PEQ, MPNP, etc.).", es: "Test de posicionamiento lingüístico + análisis de su expediente para identificar el programa óptimo.", it: "Test di posizionamento linguistico + analisi del vostro dossier per identificare il programma ottimale.", pt: "Teste de posicionamento linguístico + análise do seu dossiê para identificar o programa ideal.", de: "Sprachstandstest + Analyse Ihrer Akte zur Ermittlung des optimalen Programms.", ht: "Tès pozisyonman lengwistik + analiz dosye ou pou idantifye pwogram optimal la." },
  "imm.s2.title": { fr: "Préparation au TEF / TCF", en: "TEF / TCF preparation", es: "Preparación TEF / TCF", it: "Preparazione TEF / TCF", pt: "Preparação TEF / TCF", de: "TEF / TCF-Vorbereitung", ht: "Preparasyon TEF / TCF" },
  "imm.s2.desc": { fr: "Cours ciblés sur votre objectif de niveau (CLB) et simulations en conditions d'examen, pour aborder le test avec confiance.", en: "Courses targeted at your level goal (CLB) and exam-condition simulations, to approach the test with confidence.", es: "Cursos orientados a su objetivo de nivel (CLB) y simulaciones en condiciones de examen, para abordar la prueba con confianza.", it: "Corsi mirati al vostro obiettivo di livello (CLB) e simulazioni in condizioni d'esame, per affrontare il test con fiducia.", pt: "Cursos focados no seu objetivo de nível (CLB) e simulações em condições de exame, para abordar o teste com confiança.", de: "Auf Ihr Niveauziel (CLB) ausgerichtete Kurse und Simulationen unter Prüfungsbedingungen, um den Test selbstbewusst anzugehen.", ht: "Kou vize sou objektif nivo ou (CLB) ak similasyon nan kondisyon egzamen, pou abòde tès la ak konfyans." },
  "imm.s3.title": { fr: "Comprendre les démarches", en: "Understanding the process", es: "Comprender los trámites", it: "Comprendere le procedure", pt: "Compreender as etapas", de: "Die Schritte verstehen", ht: "Konprann demach yo" },
  "imm.s3.desc": { fr: "Ressources d'information générale sur les formulaires et les étapes. ARCADINS ne fournit pas de conseil juridique en immigration ; consultez un professionnel autorisé.", en: "General information resources on forms and steps. ARCADINS does not provide legal immigration advice; consult an authorized professional.", es: "Recursos de información general sobre formularios y etapas. ARCADINS no ofrece asesoría jurídica en inmigración; consulte a un profesional autorizado.", it: "Risorse di informazione generale su moduli e procedure. ARCADINS non fornisce consulenza legale in materia di immigrazione; rivolgetevi a un professionista autorizzato.", pt: "Recursos de informação geral sobre formulários e etapas. A ARCADINS não fornece aconselhamento jurídico em imigração; consulte um profissional autorizado.", de: "Allgemeine Informationsressourcen zu Formularen und Schritten. ARCADINS bietet keine rechtliche Einwanderungsberatung; wenden Sie sich an eine autorisierte Fachperson.", ht: "Resous enfòmasyon jeneral sou fòmilè ak etap yo. ARCADINS pa bay konsèy jiridik nan imigrasyon; konsilte yon pwofesyonèl otorize." },
  "imm.s4.title": { fr: "Intégration & Emploi au Québec", en: "Integration & Employment in Quebec", es: "Integración & Empleo en Quebec", it: "Integrazione & Lavoro in Quebec", pt: "Integração & Emprego em Quebec", de: "Integration & Beschäftigung in Quebec", ht: "Entegrasyon & Travay nan Quebec" },
  "imm.s4.desc": { fr: "Coaching d'insertion professionnelle : CV adapté au marché canadien et préparation aux entretiens d'embauche.", en: "Professional integration coaching: a CV adapted to the Canadian market and job interview preparation.", es: "Coaching de inserción profesional: CV adaptado al mercado canadiense y preparación para entrevistas.", it: "Coaching di inserimento professionale: CV adattato al mercato canadese e preparazione ai colloqui.", pt: "Coaching de inserção profissional: CV adaptado ao mercado canadense e preparação para entrevistas.", de: "Coaching zur beruflichen Eingliederung: an den kanadischen Markt angepasster Lebenslauf und Vorbereitung auf Vorstellungsgespräche.", ht: "Coaching ensèsyon pwofesyonèl: CV adapte pou mache kanadyen an ak preparasyon pou entèvyou travay." },

  // ═══ TEMOIGNAGES PAGE ═══
  "testi.label": { fr: "Témoignages", en: "Testimonials", es: "Testimonios", it: "Testimonianze", pt: "Depoimentos", de: "Erfahrungen", ht: "Temwayaj" },
  "testi.title1": { fr: "Ce que disent nos", en: "What our", es: "Lo que dicen nuestros", it: "Cosa dicono i nostri", pt: "O que dizem nossos", de: "Was unsere", ht: "Sa" },
  "testi.title2": { fr: "diplômés", en: "graduates say", es: "graduados", it: "diplomati", pt: "formados", de: "Absolventen sagen", ht: "diplome yo di" },
  "testi.empty": { fr: "Les premiers témoignages de nos apprenants seront publiés ici, avec leur consentement. Vous suivez une formation ARCADINS et souhaitez partager votre expérience ? Écrivez-nous.", en: "The first testimonials from our learners will be published here, with their consent. Are you taking an ARCADINS program and would like to share your experience? Write to us.", es: "Los primeros testimonios de nuestros estudiantes se publicarán aquí, con su consentimiento. ¿Estás siguiendo una formación ARCADINS y quieres compartir tu experiencia? Escríbenos.", it: "Le prime testimonianze dei nostri studenti saranno pubblicate qui, con il loro consenso. Stai seguendo un corso ARCADINS e vuoi condividere la tua esperienza? Scrivici.", pt: "Os primeiros depoimentos dos nossos alunos serão publicados aqui, com o seu consentimento. Está a fazer uma formação ARCADINS e quer partilhar a sua experiência? Escreva-nos.", de: "Die ersten Erfahrungsberichte unserer Lernenden werden hier mit deren Zustimmung veröffentlicht. Absolvieren Sie ein ARCADINS-Programm und möchten Ihre Erfahrung teilen? Schreiben Sie uns.", ht: "Premye temwayaj apranti nou yo pral pibliye isit la, ak konsantman yo. Èske w ap swiv yon fòmasyon ARCADINS epi ou vle pataje eksperyans ou? Ekri nou." },

  // ═══ CONTACT PAGE ═══
  "contact.label": { fr: "Nous contacter", en: "Contact Us", es: "Contáctenos", it: "Contattaci", pt: "Fale conosco", de: "Kontakt", ht: "Kontakte nou" },
  "contact.title1": { fr: "Parlons de", en: "Let's talk about", es: "Hablemos de", it: "Parliamo del", pt: "Vamos falar sobre", de: "Lassen Sie uns über", ht: "Ann pale de" },
  "contact.title2": { fr: "votre", en: "your", es: "su", it: "vostro", pt: "seu", de: "Ihr", ht: "ou" },
  "contact.title3": { fr: "projet", en: "project", es: "proyecto", it: "progetto", pt: "projeto", de: "Projekt sprechen", ht: "pwojè" },
  "contact.desc": { fr: "Notre équipe multilingue est disponible pour vous orienter vers le programme et le forfait les mieux adaptés à votre objectif.", en: "Our multilingual team is available to guide you toward the program and package best suited to your goal.", es: "Nuestro equipo multilingüe está disponible para orientarle hacia el programa y el plan más adecuados a su objetivo.", it: "Il nostro team multilingue è disponibile per orientarvi verso il programma e il pacchetto più adatti al vostro obiettivo.", pt: "Nossa equipe multilíngue está disponível para orientá-lo ao programa e pacote mais adequados ao seu objetivo.", de: "Unser mehrsprachiges Team steht Ihnen zur Verfügung, um Sie zum am besten geeigneten Programm und Paket zu beraten.", ht: "Ekip miltileng nou an disponib pou gide ou nan pwogram ak fòfè ki pi adapte ak objektif ou." },
  "contact.form.title": { fr: "Demande de renseignements", en: "Information Request", es: "Solicitud de información", it: "Richiesta di informazioni", pt: "Pedido de informações", de: "Informationsanfrage", ht: "Demann enfòmasyon" },
  "contact.form.first": { fr: "Prénom *", en: "First Name *", es: "Nombre *", it: "Nome *", pt: "Nome *", de: "Vorname *", ht: "Prenon *" },
  "contact.form.last": { fr: "Nom *", en: "Last Name *", es: "Apellido *", it: "Cognome *", pt: "Sobrenome *", de: "Nachname *", ht: "Non *" },
  "contact.form.email": { fr: "Courriel *", en: "Email *", es: "Correo *", it: "Email *", pt: "Email *", de: "E-Mail *", ht: "Imèl *" },
  "contact.form.country": { fr: "Pays de résidence", en: "Country of residence", es: "País de residencia", it: "Paese di residenza", pt: "País de residência", de: "Wohnsitzland", ht: "Peyi rezidans" },
  "contact.form.interest": { fr: "Je suis intéressé(e) par", en: "I am interested in", es: "Estoy interesado/a en", it: "Sono interessato/a a", pt: "Estou interessado/a em", de: "Ich interessiere mich für", ht: "Mwen enterese nan" },
  "contact.form.message": { fr: "Message", en: "Message", es: "Mensaje", it: "Messaggio", pt: "Mensagem", de: "Nachricht", ht: "Mesaj" },
  "contact.form.submit": { fr: "Envoyer ma demande →", en: "Send my request →", es: "Enviar mi solicitud →", it: "Invia la mia richiesta →", pt: "Enviar meu pedido →", de: "Anfrage senden →", ht: "Voye demann mwen →" },
  "contact.form.sent": { fr: "✓ Envoyé — Réponse sous 24h", en: "✓ Sent — Response within 24h", es: "✓ Enviado — Respuesta en 24h", it: "✓ Inviato — Risposta entro 24h", pt: "✓ Enviado — Resposta em 24h", de: "✓ Gesendet — Antwort innerhalb 24h", ht: "✓ Voye — Repons nan 24è" },
  "contact.form.sending": { fr: "Envoi en cours...", en: "Sending...", es: "Enviando...", it: "Invio in corso...", pt: "Enviando...", de: "Wird gesendet...", ht: "Ap voye..." },
  "contact.form.note": { fr: "Nous répondons généralement sous 24h · Consultation initiale gratuite", en: "We usually reply within 24h · Free initial consultation", es: "Solemos responder en 24h · Consulta inicial gratuita", it: "Di solito rispondiamo entro 24h · Consulenza iniziale gratuita", pt: "Costumamos responder em 24h · Consulta inicial gratuita", de: "Wir antworten in der Regel innerhalb von 24h · Kostenlose Erstberatung", ht: "Nou jeneralman reponn nan 24è · Premye konsiltasyon gratis" },
  "contact.form.address": { fr: "Adresse", en: "Address", es: "Dirección", it: "Indirizzo", pt: "Endereço", de: "Adresse", ht: "Adrès" },
  "contact.form.phone": { fr: "Téléphone", en: "Phone", es: "Teléfono", it: "Telefono", pt: "Telefone", de: "Telefon", ht: "Telefòn" },

  // ═══ TARIFS PAGE ═══
  "tarifs.label": { fr: "Tarifs & Forfaits", en: "Pricing & Plans", es: "Precios & Planes", it: "Prezzi & Piani", pt: "Preços & Planos", de: "Preise & Pläne", ht: "Pri & Plan" },
  "tarifs.title1": { fr: "Des plans adaptés à", en: "Plans adapted to", es: "Planes adaptados a", it: "Piani adattati a", pt: "Planos adaptados a", de: "Pläne angepasst an", ht: "Plan adapte pou" },
  "tarifs.title2": { fr: "chaque", en: "every", es: "cada", it: "ogni", pt: "cada", de: "jede", ht: "chak" },
  "tarifs.title3": { fr: "parcours", en: "journey", es: "camino", it: "percorso", pt: "jornada", de: "Weg", ht: "pous" },
  "tarifs.desc": { fr: "Paiements acceptés en CAD, USD, EUR et paiements mobiles africains.", en: "Payments accepted in CAD, USD, EUR and African mobile payments.", es: "Pagos aceptados en CAD, USD, EUR y pagos móviles africanos.", it: "Pagamenti accettati in CAD, USD, EUR e pagamenti mobili africani.", pt: "Pagamentos aceitos em CAD, USD, EUR e pagamentos móveis africanos.", de: "Zahlungen akzeptiert in CAD, USD, EUR und afrikanische mobile Zahlungen.", ht: "Peman aksepte an CAD, USD, EUR ak peman mobil afriken." },
  "tarifs.monthly": { fr: "Mensuel", en: "Monthly", es: "Mensual", it: "Mensile", pt: "Mensal", de: "Monatlich", ht: "Chak mwa" },
  "tarifs.annual": { fr: "Annuel", en: "Annual", es: "Anual", it: "Annuale", pt: "Anual", de: "Jährlich", ht: "Chak ane" },
  "tarifs.payments": { fr: "Modes de paiement acceptés", en: "Accepted payment methods", es: "Métodos de pago aceptados", it: "Metodi di pagamento accettati", pt: "Métodos de pagamento aceitos", de: "Akzeptierte Zahlungsmethoden", ht: "Metòd peman aksepte" },
  "tarifs.custom": { fr: "Sur mesure", en: "Custom", es: "A medida", it: "Su misura", pt: "Sob medida", de: "Maßgeschneidert", ht: "Sou mezir" },
  "tarifs.month": { fr: "/mois", en: "/month", es: "/mes", it: "/mese", pt: "/mês", de: "/Monat", ht: "/mwa" },

  // ═══ AUTH ═══
  "auth.login": { fr: "Connexion", en: "Sign In", es: "Iniciar sesión", it: "Accesso", pt: "Entrar", de: "Anmelden", ht: "Konekte" },
  "auth.login.desc": { fr: "Accédez à votre espace étudiant ARCADINS", en: "Access your ARCADINS student space", es: "Acceda a su espacio de estudiante ARCADINS", it: "Accedi al tuo spazio studente ARCADINS", pt: "Acesse seu espaço de estudante ARCADINS", de: "Zugang zu Ihrem ARCADINS-Studienbereich", ht: "Aksede espas etidyan ARCADINS ou" },
  "auth.login.btn": { fr: "Se connecter →", en: "Sign in →", es: "Iniciar sesión →", it: "Accedi →", pt: "Entrar →", de: "Anmelden →", ht: "Konekte →" },
  "auth.login.no_account": { fr: "Pas encore de compte ?", en: "Don't have an account?", es: "¿No tiene cuenta?", it: "Non hai un account?", pt: "Não tem conta?", de: "Noch kein Konto?", ht: "Pa gen kont?" },
  "auth.register": { fr: "Créer un compte", en: "Create Account", es: "Crear cuenta", it: "Crea account", pt: "Criar conta", de: "Konto erstellen", ht: "Kreye kont" },
  "auth.register.desc": { fr: "Créez votre compte et commencez votre préparation", en: "Create your account and start your preparation", es: "Cree su cuenta y comience su preparación", it: "Crea il tuo account e inizia la tua preparazione", pt: "Crie a sua conta e comece a sua preparação", de: "Erstellen Sie Ihr Konto und beginnen Sie Ihre Vorbereitung", ht: "Kreye kont ou epi kòmanse preparasyon ou" },
  "auth.register.btn": { fr: "Créer mon compte →", en: "Create my account →", es: "Crear mi cuenta →", it: "Crea il mio account →", pt: "Criar minha conta →", de: "Mein Konto erstellen →", ht: "Kreye kont mwen →" },
  "auth.register.has_account": { fr: "Déjà inscrit ?", en: "Already registered?", es: "¿Ya registrado?", it: "Già registrato?", pt: "Já cadastrado?", de: "Bereits registriert?", ht: "Deja enskri?" },
  "auth.password": { fr: "Mot de passe", en: "Password", es: "Contraseña", it: "Password", pt: "Senha", de: "Passwort", ht: "Modpas" },

  // ═══ DASHBOARD ═══
  "dash.label": { fr: "Espace Étudiant", en: "Student Space", es: "Espacio Estudiante", it: "Area Studente", pt: "Espaço do Aluno", de: "Studienbereich", ht: "Espas Etidyan" },
  "dash.welcome": { fr: "Bienvenue,", en: "Welcome,", es: "Bienvenido,", it: "Benvenuto,", pt: "Bem-vindo,", de: "Willkommen,", ht: "Byenveni," },
  "dash.manage": { fr: "Gérez vos formations, examens et certificats.", en: "Manage your training, exams and certificates.", es: "Gestione sus formaciones, exámenes y certificados.", it: "Gestisci le tue formazioni, esami e certificati.", pt: "Gerencie suas formações, exames e certificados.", de: "Verwalten Sie Ihre Ausbildungen, Prüfungen und Zertifikate.", ht: "Jere fòmasyon, egzamen ak sètifika ou yo." },
  "dash.start": { fr: "Commencez votre parcours", en: "Start your journey", es: "Comience su camino", it: "Inizia il tuo percorso", pt: "Comece sua jornada", de: "Starten Sie Ihren Weg", ht: "Kòmanse pous ou" },
  "dash.no_formations": { fr: "Vous n'avez pas encore de formation active. Explorez nos programmes et commencez votre préparation dès aujourd'hui.", en: "You don't have any active training yet. Explore our programs and start your preparation today.", es: "Aún no tiene formación activa. Explore nuestros programas y comience su preparación hoy.", it: "Non hai ancora formazione attiva. Esplora i nostri programmi e inizia la tua preparazione oggi.", pt: "Você ainda não tem formação ativa. Explore nossos programas e comece sua preparação hoje.", de: "Sie haben noch keine aktive Ausbildung. Entdecken Sie unsere Programme und beginnen Sie heute mit Ihrer Vorbereitung.", ht: "Ou poko gen fòmasyon aktif. Eksplore pwogram nou yo epi kòmanse preparasyon ou jodi a." },
  "dash.profile": { fr: "Mon profil", en: "My Profile", es: "Mi perfil", it: "Il mio profilo", pt: "Meu perfil", de: "Mein Profil", ht: "Pwofil mwen" },

  // ═══ COURSE NAMES ═══
  "c.marketing-digital": { fr: "Marketing Digital et E-commerce", en: "Digital Marketing & E-commerce", es: "Marketing Digital y E-commerce", it: "Marketing Digitale ed E-commerce", pt: "Marketing Digital e E-commerce", de: "Digitales Marketing & E-Commerce", ht: "Maketing Dijital ak E-komès" },
  "c.informatique": { fr: "Informatique et Transformation Digitale", en: "IT & Digital Transformation", es: "Informática y Transformación Digital", it: "Informatica e Trasformazione Digitale", pt: "Informática e Transformação Digital", de: "Informatik & Digitale Transformation", ht: "Enfòmatik ak Transfòmasyon Dijital" },
  "c.francais-affaires": { fr: "Français des Affaires et du Travail", en: "Business & Workplace French", es: "Francés de Negocios y del Trabajo", it: "Francese degli Affari e del Lavoro", pt: "Francês de Negócios e do Trabalho", de: "Wirtschafts- und Berufsfranzösisch", ht: "Fransè Biznis ak Travay" },
  "c.entrepreneuriat": { fr: "Entrepreneuriat et Innovation", en: "Entrepreneurship & Innovation", es: "Emprendimiento e Innovación", it: "Imprenditorialità e Innovazione", pt: "Empreendedorismo e Inovação", de: "Unternehmertum & Innovation", ht: "Antreprenarya ak Inovasyon" },
  "c.finance": { fr: "Gestion Financière et Comptabilité", en: "Financial Management & Accounting", es: "Gestión Financiera y Contabilidad", it: "Gestione Finanziaria e Contabilità", pt: "Gestão Financeira e Contabilidade", de: "Finanzmanagement & Buchhaltung", ht: "Jesyon Finansye ak Kontabilite" },
  "c.rh": { fr: "Gestion des Ressources Humaines", en: "Human Resources Management", es: "Gestión de Recursos Humanos", it: "Gestione delle Risorse Umane", pt: "Gestão de Recursos Humanos", de: "Personalmanagement", ht: "Jesyon Resous Imèn" },
  "c.tourisme": { fr: "Tourisme et Gestion Hôtelière", en: "Tourism & Hotel Management", es: "Turismo y Gestión Hotelera", it: "Turismo e Gestione Alberghiera", pt: "Turismo e Gestão Hoteleira", de: "Tourismus & Hotelmanagement", ht: "Touris ak Jesyon Otèl" },
  "c.anglais-commercial": { fr: "Anglais Commercial", en: "Business English", es: "Inglés Comercial", it: "Inglese Commerciale", pt: "Inglês Comercial", de: "Wirtschaftsenglisch", ht: "Anglè Komèsyal" },
  "c.relation-aide": { fr: "Relation d'Aide et Service Communautaire", en: "Counseling & Community Services", es: "Relación de Ayuda y Servicio Comunitario", it: "Relazione d'Aiuto e Servizio Comunitario", pt: "Relação de Ajuda e Serviço Comunitário", de: "Beratung & Gemeinschaftsdienst", ht: "Relasyon Èd ak Sèvis Kominotè" },
  "c.francais-tef-tcf": { fr: "Français Intensif TEF/TCF Canada", en: "Intensive French TEF/TCF Canada", es: "Francés Intensivo TEF/TCF Canadá", it: "Francese Intensivo TEF/TCF Canada", pt: "Francês Intensivo TEF/TCF Canadá", de: "Intensiv-Französisch TEF/TCF Kanada", ht: "Fransè Entansif TEF/TCF Kanada" },
  "c.epe": { fr: "Éducatrice à la Petite Enfance (EPE)", en: "Early Childhood Educator (ECE)", es: "Educadora de Primera Infancia (EPE)", it: "Educatrice della Prima Infanzia (EPE)", pt: "Educadora da Primeira Infância (EPE)", de: "Frühkindliche Erzieherin (EPE)", ht: "Edikatris Timoun Piti (EPE)" },
  "c.pab": { fr: "Préposé(e) aux Bénéficiaires (PAB)", en: "Patient Attendant (PAB)", es: "Asistente de Pacientes (PAB)", it: "Assistente ai Pazienti (PAB)", pt: "Assistente de Pacientes (PAB)", de: "Patientenbetreuer/in (PAB)", ht: "Prépoze Benefisyè (PAB)" },
  "c.immigration-agent": { fr: "Agent(e) de Soutien en Immigration", en: "Immigration Support Agent", es: "Agente de Apoyo en Inmigración", it: "Agente di Supporto all'Immigrazione", pt: "Agente de Apoio à Imigração", de: "Einwanderungsberater/in", ht: "Ajan Sipò Imigrasyon" },
  "c.famille-sans-dette": { fr: "Famille Sans Dette", en: "Debt-Free Family", es: "Familia Sin Deudas", it: "Famiglia Senza Debiti", pt: "Família Sem Dívidas", de: "Schuldenfreie Familie", ht: "Fanmi San Dèt" },

  // ═══ COURSE DESCRIPTIONS ═══
  "cd.marketing-digital": { fr: "SEO/SEM, réseaux sociaux, publicité en ligne et création de boutiques e-commerce.", en: "SEO/SEM, social media, online advertising and e-commerce store creation.", es: "SEO/SEM, redes sociales, publicidad en línea y creación de tiendas e-commerce.", it: "SEO/SEM, social media, pubblicità online e creazione di negozi e-commerce.", pt: "SEO/SEM, redes sociais, publicidade online e criação de lojas e-commerce.", de: "SEO/SEM, Social Media, Online-Werbung und E-Commerce-Shop-Erstellung.", ht: "SEO/SEM, rezo sosyal, piblisite sou entènèt ak kreye boutik e-komès." },
  "cd.informatique": { fr: "Cloud computing, IA appliquée, cybersécurité et digitalisation des processus d'entreprise.", en: "Cloud computing, applied AI, cybersecurity and enterprise digital transformation.", es: "Computación en la nube, IA aplicada, ciberseguridad y transformación digital empresarial.", it: "Cloud computing, IA applicata, cybersicurezza e trasformazione digitale aziendale.", pt: "Computação em nuvem, IA aplicada, cibersegurança e transformação digital empresarial.", de: "Cloud Computing, angewandte KI, Cybersicherheit und digitale Unternehmenstransformation.", ht: "Cloud computing, IA aplike, sibèsekirite ak transfòmasyon dijital antrepriz." },
  "cd.francais-affaires": { fr: "Vocabulaire professionnel, communication d'entreprise et français québécois du milieu de travail.", en: "Professional vocabulary, business communication and Quebec workplace French.", es: "Vocabulario profesional, comunicación empresarial y francés quebequense laboral.", it: "Vocabolario professionale, comunicazione aziendale e francese quebecchese lavorativo.", pt: "Vocabulário profissional, comunicação empresarial e francês quebequense profissional.", de: "Berufsvokabular, Unternehmenskommunikation und Quebec-Französisch am Arbeitsplatz.", ht: "Vokabilè pwofesyonèl, kominikasyon biznis ak fransè kebekwa travay." },
  "cd.entrepreneuriat": { fr: "Créer et gérer une entreprise au Canada. Plan d'affaires, financement et innovation.", en: "Create and manage a business in Canada. Business plan, financing and innovation.", es: "Crear y gestionar una empresa en Canadá. Plan de negocios, financiamiento e innovación.", it: "Creare e gestire un'impresa in Canada. Business plan, finanziamento e innovazione.", pt: "Criar e gerir uma empresa no Canadá. Plano de negócios, financiamento e inovação.", de: "Ein Unternehmen in Kanada gründen und führen. Geschäftsplan, Finanzierung und Innovation.", ht: "Kreye ak jere yon biznis nan Kanada. Plan biznis, finansman ak inovasyon." },
  "cd.finance": { fr: "Analyse de bilan, planification budgétaire, comptabilité et fiscalité canadienne.", en: "Balance sheet analysis, budget planning, accounting and Canadian taxation.", es: "Análisis de balances, planificación presupuestaria, contabilidad y fiscalidad canadiense.", it: "Analisi di bilancio, pianificazione budgetaria, contabilità e fiscalità canadese.", pt: "Análise de balanço, planejamento orçamentário, contabilidade e tributação canadense.", de: "Bilanzanalyse, Budgetplanung, Buchhaltung und kanadisches Steuerrecht.", ht: "Analiz bilan, planifikasyon bidjè, kontabilite ak fiskalize kanadyen." },
  "cd.rh": { fr: "Droit du travail québécois, recrutement, gestion des talents et relations de travail.", en: "Quebec labor law, recruitment, talent management and labor relations.", es: "Derecho laboral quebequense, reclutamiento, gestión del talento y relaciones laborales.", it: "Diritto del lavoro quebecchese, reclutamento, gestione dei talenti e relazioni di lavoro.", pt: "Direito trabalhista quebequense, recrutamento, gestão de talentos e relações de trabalho.", de: "Quebec-Arbeitsrecht, Rekrutierung, Talentmanagement und Arbeitsbeziehungen.", ht: "Dwa travay kebekwa, rekritman, jesyon talan ak relasyon travay." },
  "cd.tourisme": { fr: "Gestion hôtelière, tourisme d'accueil, événementiel et service à la clientèle premium.", en: "Hotel management, hospitality tourism, event planning and premium customer service.", es: "Gestión hotelera, turismo de acogida, eventos y servicio al cliente premium.", it: "Gestione alberghiera, turismo d'accoglienza, eventi e servizio clienti premium.", pt: "Gestão hoteleira, turismo de acolhimento, eventos e atendimento premium.", de: "Hotelmanagement, Gastfreundschaftstourismus, Veranstaltungsplanung und Premium-Kundenservice.", ht: "Jesyon otèl, touris akèy, evènman ak sèvis kliyan premium." },
  "cd.anglais-commercial": { fr: "Anglais professionnel pour le milieu des affaires canadien. Communication, négociation et rédaction.", en: "Professional English for the Canadian business environment. Communication, negotiation and writing.", es: "Inglés profesional para el entorno empresarial canadiense. Comunicación, negociación y redacción.", it: "Inglese professionale per l'ambiente aziendale canadese. Comunicazione, negoziazione e redazione.", pt: "Inglês profissional para o ambiente de negócios canadense. Comunicação, negociação e redação.", de: "Berufsenglisch für das kanadische Geschäftsumfeld. Kommunikation, Verhandlung und Schreiben.", ht: "Anglè pwofesyonèl pou anviwònman biznis kanadyen. Kominikasyon, negosyasyon ak redaksyon." },
  "cd.relation-aide": { fr: "Intervention psychosociale, accompagnement communautaire et soutien aux personnes vulnérables.", en: "Psychosocial intervention, community support and assistance for vulnerable individuals.", es: "Intervención psicosocial, acompañamiento comunitario y apoyo a personas vulnerables.", it: "Intervento psicosociale, accompagnamento comunitario e sostegno alle persone vulnerabili.", pt: "Intervenção psicossocial, acompanhamento comunitário e apoio a pessoas vulneráveis.", de: "Psychosoziale Intervention, Gemeinschaftsbegleitung und Unterstützung gefährdeter Personen.", ht: "Entèvansyon psikososyal, akonpayeman kominotè ak sipò pou moun vilnerab." },
  "cd.francais-tef-tcf": { fr: "Maîtrisez les 4 compétences linguistiques exigées pour l'immigration. Coaching oral inclus.", en: "Master the 4 language skills required for immigration. Oral coaching included.", es: "Domine las 4 competencias lingüísticas exigidas para la inmigración. Coaching oral incluido.", it: "Padroneggia le 4 competenze linguistiche richieste per l'immigrazione. Coaching orale incluso.", pt: "Domine as 4 competências linguísticas exigidas para a imigração. Coaching oral incluído.", de: "Meistern Sie die 4 für die Einwanderung erforderlichen Sprachkompetenzen. Mündliches Coaching inklusive.", ht: "Metrize 4 konpetans lengwistik egzije pou imigrasyon. Coaching oral enkli." },
  "cd.epe": { fr: "Formation reconnue Québec. Environnement éducatif 0–5 ans.", en: "Quebec-recognized training. Educational environment for ages 0–5.", es: "Formación reconocida en Quebec. Entorno educativo 0–5 años.", it: "Formazione riconosciuta in Quebec. Ambiente educativo 0–5 anni.", pt: "Formação reconhecida em Quebec. Ambiente educativo 0–5 anos.", de: "In Quebec anerkannte Ausbildung. Bildungsumgebung 0–5 Jahre.", ht: "Fòmasyon rekonèt nan Quebec. Anviwònman edikasyon 0–5 an." },
  "cd.pab": { fr: "Formation PAB reconnue MSSS Québec. Soins aux personnes vulnérables.", en: "MSSS Quebec recognized PAB training. Care for vulnerable individuals.", es: "Formación PAB reconocida MSSS Quebec. Cuidado de personas vulnerables.", it: "Formazione PAB riconosciuta MSSS Quebec. Cura delle persone vulnerabili.", pt: "Formação PAB reconhecida MSSS Quebec. Cuidados a pessoas vulneráveis.", de: "MSSS Quebec anerkannte PAB-Ausbildung. Pflege gefährdeter Personen.", ht: "Fòmasyon PAB rekonèt MSSS Quebec. Swen pou moun vilnerab." },
  "cd.immigration-agent": { fr: "Notions générales sur les démarches, formulaires et procédures d'immigration.", en: "General notions on immigration steps, forms and procedures.", es: "Nociones generales sobre trámites, formularios y procedimientos de inmigración.", it: "Nozioni generali su procedure, moduli e pratiche di immigrazione.", pt: "Noções gerais sobre etapas, formulários e procedimentos de imigração.", de: "Allgemeine Kenntnisse zu Einwanderungsschritten, Formularen und Verfahren.", ht: "Nosyon jeneral sou demach, fòmilè ak pwosedi imigrasyon." },
  "cd.famille-sans-dette": { fr: "Budget familial, crédit, épargne et planification pour nouveaux arrivants.", en: "Family budget, credit, savings and planning for newcomers.", es: "Presupuesto familiar, crédito, ahorro y planificación para recién llegados.", it: "Budget familiare, credito, risparmio e pianificazione per nuovi arrivati.", pt: "Orçamento familiar, crédito, poupança e planejamento para recém-chegados.", de: "Familienbudget, Kredit, Sparen und Planung für Neuankömmlinge.", ht: "Bidjè fanmi, kredi, epay ak planifikasyon pou nouvo vini." },

  // Course detail labels
  "cd.coming": { fr: "Bientôt disponible", en: "Coming Soon", es: "Próximamente", it: "Prossimamente", pt: "Em breve", de: "Demnächst", ht: "Byento disponib" },
  "cd.avenir": { fr: "À Venir", en: "Coming Soon", es: "Próximamente", it: "Prossimamente", pt: "Em breve", de: "Demnächst", ht: "Ap vini" },
  "cd.certified": { fr: "Certifié", en: "Certified", es: "Certificado", it: "Certificato", pt: "Certificado", de: "Zertifiziert", ht: "Sètifye" },
};
