import type { BankQuestion } from "@/lib/academic/types";

/**
 * Banque de questions — Marketing Digital v2.
 * ÉTAT : Module 1 rédigé comme exemplaire de référence (20 questions, difficulté et types variés).
 * Modules 2–8 : à rédiger module par module (voir MARKETING_QUESTION_BANK_AUDIT.md).
 *
 * SÉCURITÉ : `correct` ne doit jamais transiter vers le client public — la correction est serveur.
 */
export const marketingDigitalV2Bank: BankQuestion[] = [
  {
    id: "mkt-v2-m1-q01",
    module: 1,
    week: 1,
    objectiveRef: "C1",
    difficulty: "easy",
    type: "mcq",
    prompt: "Qu'est-ce qui distingue fondamentalement le marketing digital du marketing traditionnel ?",
    options: [
      "Il est toujours moins cher",
      "Il permet de mesurer précisément chaque interaction et d'ajuster en temps réel",
      "Il ne nécessite aucune stratégie",
      "Il touche uniquement les jeunes",
    ],
    correct: [1],
    explanation:
      "La mesurabilité et l'agilité (ajustement en temps réel) sont les traits distinctifs, pas le coût ni l'audience.",
    feedbackOnError: "Revoyez la notion de mesurabilité : chaque impression, clic et achat est traçable.",
    tags: ["fondamentaux", "définition"],
    editorialStatus: "approved",
  },
  {
    id: "mkt-v2-m1-q02",
    module: 1,
    week: 1,
    objectiveRef: "C1",
    difficulty: "easy",
    type: "mcq",
    prompt: "Dans le modèle AARRR, que signifie la première lettre « A » ?",
    options: ["Analytics", "Acquisition", "Activation", "Ads"],
    correct: [1],
    explanation: "AARRR = Acquisition, Activation, Rétention, Recommandation, Revenu.",
    feedbackOnError: "La première étape attire du trafic : c'est l'Acquisition.",
    tags: ["funnel", "AARRR"],
    editorialStatus: "approved",
  },
  {
    id: "mkt-v2-m1-q03",
    module: 1,
    week: 1,
    objectiveRef: "C2",
    difficulty: "medium",
    type: "multi",
    prompt: "Parmi les éléments suivants, lesquels appartiennent au modèle AARRR ? (plusieurs réponses)",
    options: ["Rétention", "Recommandation", "Rentabilité brute", "Activation"],
    correct: [0, 1, 3],
    explanation: "AARRR contient Rétention, Recommandation et Activation ; « Rentabilité brute » n'en fait pas partie.",
    feedbackOnError: "Rappelez-vous : Acquisition, Activation, Rétention, Recommandation, Revenu.",
    tags: ["funnel", "AARRR"],
    editorialStatus: "approved",
  },
  {
    id: "mkt-v2-m1-q04",
    module: 1,
    week: 2,
    objectiveRef: "C2",
    difficulty: "medium",
    type: "scenario",
    prompt:
      "Une boutique attire 5 000 visiteurs/mois mais 93 % quittent la fiche produit sans rien ajouter au panier. Où se situe la fuite du funnel ?",
    options: ["Acquisition", "Activation", "Recommandation", "Revenu"],
    correct: [1],
    explanation:
      "Le trafic arrive (Acquisition OK) mais la conversion échoue : la fuite est à l'Activation. Augmenter le budget pub n'y changerait rien.",
    feedbackOnError: "Le trafic est bon ; le problème est la conversion des visiteurs en action.",
    tags: ["funnel", "diagnostic"],
    editorialStatus: "approved",
  },
  {
    id: "mkt-v2-m1-q05",
    module: 1,
    week: 2,
    objectiveRef: "C3",
    difficulty: "medium",
    type: "mcq",
    prompt: "Qu'est-ce qu'un persona en marketing ?",
    options: [
      "Le nom commercial d'un produit",
      "La représentation semi-fictive du client idéal (habitudes, freins, canaux)",
      "Un influenceur payé",
      "Le logo d'une marque",
    ],
    correct: [1],
    explanation: "Le persona synthétise le client idéal pour guider le choix des messages et des canaux.",
    feedbackOnError: "Un persona décrit un type de client, pas un produit ni une marque.",
    tags: ["persona", "ciblage"],
    editorialStatus: "approved",
  },
  {
    id: "mkt-v2-m1-q06",
    module: 1,
    week: 2,
    objectiveRef: "C3",
    difficulty: "hard",
    type: "scenario",
    prompt:
      "Un logiciel B2B à cycle de vente de 4 mois avec plusieurs décideurs. Quelle approche est la plus cohérente ?",
    options: [
      "Une campagne d'achat impulsif sur TikTok",
      "Un contenu éducatif et un nurturing par email/LinkedIn adapté au cycle long",
      "Des soldes flash quotidiennes",
      "Uniquement des publicités display génériques",
    ],
    correct: [1],
    explanation:
      "Un cycle B2B long et multi-décideurs se travaille par contenu de fond et nurturing, pas par l'impulsion.",
    feedbackOnError: "Adaptez le canal et le message au cycle de vente et au persona, pas à la mode.",
    tags: ["persona", "B2B", "canaux"],
    editorialStatus: "approved",
  },
  {
    id: "mkt-v2-m1-q07",
    module: 1,
    week: 1,
    objectiveRef: "C2",
    difficulty: "easy",
    type: "mcq",
    prompt: "Pourquoi attirer davantage de trafic est-il inutile si le site ne convertit pas ?",
    options: [
      "Parce que le trafic coûte cher",
      "Parce que la fuite du funnel est en aval : plus de visiteurs = plus de pertes au même endroit",
      "Parce que Google le pénalise",
      "Parce que le trafic ralentit le site",
    ],
    correct: [1],
    explanation: "On corrige d'abord l'étape qui fuit ; sinon on amplifie simplement la perte.",
    feedbackOnError: "Identifiez l'étape qui fuit avant d'investir en amont.",
    tags: ["funnel", "priorisation"],
    editorialStatus: "approved",
  },
  {
    id: "mkt-v2-m1-q08",
    module: 1,
    week: 3,
    objectiveRef: "C4",
    difficulty: "medium",
    type: "calc",
    prompt:
      "Une campagne coûte 800 $ et génère 40 nouveaux clients. Quel est le coût d'acquisition client (CAC) ?",
    options: ["20 $", "32 $", "40 $", "80 $"],
    correct: [0],
    explanation: "CAC = dépense / clients acquis = 800 / 40 = 20 $.",
    feedbackOnError: "CAC = coût total ÷ nombre de clients acquis.",
    tags: ["CAC", "calcul"],
    editorialStatus: "approved",
  },
  {
    id: "mkt-v2-m1-q09",
    module: 1,
    week: 3,
    objectiveRef: "C4",
    difficulty: "hard",
    type: "calc",
    prompt:
      "CAC = 20 $ et valeur vie client (LTV) = 60 $. Quel est le ratio LTV/CAC, et est-il sain ?",
    options: [
      "0,33 — sain",
      "3 — sain (repère courant ≥ 3)",
      "3 — malsain",
      "1,2 — sain",
    ],
    correct: [1],
    explanation: "LTV/CAC = 60/20 = 3. Un ratio ≥ 3 est généralement considéré comme sain.",
    feedbackOnError: "Ratio = LTV ÷ CAC ; comparez ensuite au repère de 3.",
    tags: ["LTV", "CAC", "calcul"],
    editorialStatus: "approved",
  },
  {
    id: "mkt-v2-m1-q10",
    module: 1,
    week: 2,
    objectiveRef: "C3",
    difficulty: "easy",
    type: "mcq",
    prompt: "Quelle est l'erreur la plus fréquente du marketing digital débutant ?",
    options: [
      "Mesurer trop souvent ses résultats",
      "Choisir un canal parce qu'il est « à la mode » plutôt que parce que le public cible s'y trouve",
      "Créer un persona",
      "Segmenter son audience",
    ],
    correct: [1],
    explanation: "Suivre la mode plutôt que le persona gaspille le budget.",
    feedbackOnError: "Le bon canal est celui où se trouve votre persona, pas le plus tendance.",
    tags: ["canaux", "erreurs"],
    editorialStatus: "approved",
  },
  {
    id: "mkt-v2-m1-q11",
    module: 1,
    week: 1,
    objectiveRef: "C1",
    difficulty: "medium",
    type: "mcq",
    prompt: "Lequel de ces canaux relève typiquement du marketing digital ?",
    options: ["Panneau d'autoroute", "Publicité radio locale", "Référencement sur moteur de recherche (SEO)", "Encart dans un journal papier"],
    correct: [2],
    explanation: "Le SEO est un canal numérique ; les trois autres sont traditionnels.",
    feedbackOnError: "Un canal digital passe par un support numérique mesurable.",
    tags: ["canaux", "définition"],
    editorialStatus: "approved",
  },
  {
    id: "mkt-v2-m1-q12",
    module: 1,
    week: 3,
    objectiveRef: "C4",
    difficulty: "medium",
    type: "interpret",
    prompt:
      "Tableau : Canal A — 100 clics, 5 ventes ; Canal B — 400 clics, 8 ventes. Quel canal a le meilleur taux de conversion ?",
    options: ["Canal A (5 %)", "Canal B (2 %)", "Ils sont égaux", "Impossible à dire"],
    correct: [0],
    explanation: "A = 5/100 = 5 % ; B = 8/400 = 2 %. A convertit mieux malgré moins de clics.",
    feedbackOnError: "Taux de conversion = ventes ÷ clics ; comparez les pourcentages, pas les volumes bruts.",
    tags: ["conversion", "interprétation"],
    editorialStatus: "approved",
  },
  {
    id: "mkt-v2-m1-q13",
    module: 1,
    week: 2,
    objectiveRef: "C3",
    difficulty: "hard",
    type: "analysis",
    prompt:
      "Une PME veut lancer un produit destiné aux 18-24 ans très actifs en vidéo courte. Quel plan de canaux est le plus défendable ?",
    options: [
      "Journaux papier + radio",
      "TikTok/Instagram Reels en priorité, avec mesure du coût par acquisition",
      "Email de masse acheté à un tiers",
      "Uniquement des affiches en magasin",
    ],
    correct: [1],
    explanation:
      "Le persona jeune consomme de la vidéo courte : la priorité va aux plateformes correspondantes, avec suivi du CAC.",
    feedbackOnError: "Alignez le canal sur les habitudes du persona et gardez la mesure.",
    tags: ["canaux", "persona", "analyse"],
    editorialStatus: "approved",
  },
  {
    id: "mkt-v2-m1-q14",
    module: 1,
    week: 1,
    objectiveRef: "C2",
    difficulty: "easy",
    type: "mcq",
    prompt: "Dans le funnel, à quelle étape correspond « transformer un client satisfait en ambassadeur » ?",
    options: ["Acquisition", "Activation", "Recommandation", "Revenu"],
    correct: [2],
    explanation: "La Recommandation transforme les clients en promoteurs de la marque.",
    feedbackOnError: "L'ambassadeur recommande : c'est l'étape Recommandation.",
    tags: ["funnel", "AARRR"],
    editorialStatus: "approved",
  },
  {
    id: "mkt-v2-m1-q15",
    module: 1,
    week: 3,
    objectiveRef: "C4",
    difficulty: "medium",
    type: "mcq",
    prompt: "Quel indicateur mesure directement l'efficacité budgétaire de l'acquisition ?",
    options: ["Nombre d'abonnés", "Coût d'acquisition client (CAC)", "Nombre de « j'aime »", "Nombre de pages du site"],
    correct: [1],
    explanation: "Le CAC relie la dépense au nombre de clients réellement acquis.",
    feedbackOnError: "Cherchez l'indicateur qui rapporte un coût à un résultat client.",
    tags: ["KPI", "CAC"],
    editorialStatus: "approved",
  },
  {
    id: "mkt-v2-m1-q16",
    module: 1,
    week: 2,
    objectiveRef: "C3",
    difficulty: "medium",
    type: "scenario",
    prompt:
      "Julie dépense 600 $/mois sur Facebook « parce que tout le monde en fait ». Quelle est la première action recommandée ?",
    options: [
      "Doubler le budget",
      "Analyser le funnel pour localiser la vraie fuite avant de dépenser plus",
      "Arrêter tout marketing",
      "Changer de logo",
    ],
    correct: [1],
    explanation:
      "Le cas Savonnerie Boréale montre que la fuite était l'Activation ; l'analyse précède toute hausse de budget.",
    feedbackOnError: "Diagnostiquez avant d'investir davantage.",
    tags: ["cas", "diagnostic"],
    editorialStatus: "approved",
  },
  {
    id: "mkt-v2-m1-q17",
    module: 1,
    week: 1,
    objectiveRef: "C1",
    difficulty: "hard",
    type: "analysis",
    prompt: "Pourquoi dit-on que le marketing digital « cesse d'être un pari pour devenir une discipline pilotée par la donnée » ?",
    options: [
      "Parce qu'il est gratuit",
      "Parce qu'on peut attribuer coûts et résultats à chaque canal et étape, et décider sur des faits",
      "Parce qu'il supprime le besoin de stratégie",
      "Parce qu'il garantit le succès",
    ],
    correct: [1],
    explanation: "L'attribution précise des coûts et résultats remplace l'intuition par la décision fondée sur les données.",
    feedbackOnError: "Le pilotage par la donnée repose sur la mesure et l'attribution.",
    tags: ["données", "définition"],
    editorialStatus: "approved",
  },
  {
    id: "mkt-v2-m1-q18",
    module: 1,
    week: 3,
    objectiveRef: "C4",
    difficulty: "easy",
    type: "mcq",
    prompt: "Un « KPI » est :",
    options: [
      "Un indicateur clé de performance",
      "Un type de publicité payante",
      "Un réseau social",
      "Un format d'image",
    ],
    correct: [0],
    explanation: "KPI = Key Performance Indicator, un indicateur clé de performance.",
    feedbackOnError: "KPI mesure la performance d'un objectif.",
    tags: ["KPI", "vocabulaire"],
    editorialStatus: "approved",
  },
  {
    id: "mkt-v2-m1-q19",
    module: 1,
    week: 2,
    objectiveRef: "C3",
    difficulty: "medium",
    type: "multi",
    prompt: "Quelles informations font partie d'un bon persona ? (plusieurs réponses)",
    options: ["Ses freins à l'achat", "Les plateformes qu'il fréquente", "Le chiffre d'affaires du concurrent", "Ses habitudes de consommation"],
    correct: [0, 1, 3],
    explanation: "Le persona décrit le client (freins, plateformes, habitudes), pas les finances d'un concurrent.",
    feedbackOnError: "Un persona reste centré sur le client cible.",
    tags: ["persona", "ciblage"],
    editorialStatus: "approved",
  },
  {
    id: "mkt-v2-m1-q20",
    module: 1,
    week: 3,
    objectiveRef: "C4",
    difficulty: "hard",
    type: "interpret",
    prompt:
      "Deux campagnes : X dépense 1 000 $ pour 25 clients ; Y dépense 1 500 $ pour 50 clients. Laquelle a le meilleur CAC ?",
    options: ["X (40 $)", "Y (30 $)", "Égalité", "X (25 $)"],
    correct: [1],
    explanation: "X : 1000/25 = 40 $ ; Y : 1500/50 = 30 $. Y a le meilleur (plus bas) CAC.",
    feedbackOnError: "Calculez le CAC de chaque campagne puis comparez ; le plus bas est le meilleur.",
    tags: ["CAC", "comparaison", "calcul"],
    editorialStatus: "approved",
  },

  // ═══════════════════ MODULE 2 — 20 questions (semaines 4–6) ═══════════════════
  // Recherche de marché (C5) : q01–q05
  {
    id: "mkt-v2-m2-q01",
    module: 2,
    week: 4,
    objectiveRef: "C5",
    difficulty: "easy",
    type: "mcq",
    prompt: "Quelles conditions sont nécessaires pour qu'un marché existe réellement ?",
    options: [
      "Un besoin, un pouvoir d'achat et une volonté d'agir",
      "Uniquement beaucoup de personnes intéressées",
      "Un produit tendance",
      "Une grande page de réseau social",
    ],
    correct: [0],
    explanation: "Un marché exige un besoin réel, la capacité de payer (solvabilité) et la volonté d'agir.",
    feedbackOnError: "Un besoin non solvable ou sans volonté d'achat n'est pas un marché.",
    tags: ["marché", "définition"],
    editorialStatus: "approved",
  },
  {
    id: "mkt-v2-m2-q02",
    module: 2,
    week: 4,
    objectiveRef: "C5",
    difficulty: "medium",
    type: "scenario",
    prompt:
      "Un entrepreneur affirme : « Mon marché fait 5 milliards, il me suffit d'en prendre 1 %. » Quel est le problème principal de ce raisonnement ?",
    options: [
      "Il sous-estime son marché",
      "Il confond le marché total (TAM) avec ce qu'il peut réellement capter (SOM), en ignorant l'accessibilité",
      "Il calcule mal le pourcentage",
      "Aucun problème, c'est un bon plan",
    ],
    correct: [1],
    explanation: "Sans canal, budget ni différenciation, ce 1 % est théorique. On planifie en SOM, pas en TAM.",
    feedbackOnError: "Revoyez la distinction TAM/SAM/SOM et la notion d'accessibilité.",
    tags: ["TAM", "SOM", "attractivité"],
    editorialStatus: "approved",
  },
  {
    id: "mkt-v2-m2-q03",
    module: 2,
    week: 4,
    objectiveRef: "C5",
    difficulty: "medium",
    type: "mcq",
    prompt: "Laquelle de ces sources est une donnée PRIMAIRE ?",
    options: [
      "Un rapport de Statistique Canada",
      "Un article sectoriel publié en ligne",
      "Des entretiens que vous menez vous-même avec 8 clients",
      "Les avis publiés sur une marketplace",
    ],
    correct: [2],
    explanation: "Les données primaires sont collectées par vous-même ; les trois autres existent déjà (secondaires).",
    feedbackOnError: "Primaire = collectée par vous ; secondaire = déjà existante.",
    tags: ["recherche", "primaire-secondaire"],
    editorialStatus: "approved",
  },
  {
    id: "mkt-v2-m2-q04",
    module: 2,
    week: 4,
    objectiveRef: "C5",
    difficulty: "medium",
    type: "scenario",
    prompt:
      "Un sondage demande : « Ne trouvez-vous pas que notre service est rapide et abordable ? » Quels défauts cette question cumule-t-elle ?",
    options: [
      "Aucun, la question est claire",
      "Elle est orientée ET double (deux idées en une)",
      "Elle est trop courte",
      "Elle manque d'options de réponse",
    ],
    correct: [1],
    explanation: "« Ne trouvez-vous pas » oriente la réponse, et « rapide et abordable » mêle deux idées : question orientée et double.",
    feedbackOnError: "Une bonne question est neutre et porte sur une seule idée.",
    tags: ["biais", "questionnaire"],
    editorialStatus: "approved",
  },
  {
    id: "mkt-v2-m2-q05",
    module: 2,
    week: 4,
    objectiveRef: "C5",
    difficulty: "hard",
    type: "interpret",
    prompt:
      "78 % des répondants à un sondage disent qu'ils « paieraient pour un nouveau service », mais après le lancement presque personne n'achète. Quelle leçon en tirer ?",
    options: [
      "Le service était mal conçu",
      "L'intention déclarée ne prédit pas fiablement le comportement réel ; il faut croiser déclaratif et comportement",
      "Le sondage aurait dû avoir plus de répondants",
      "Les gens ont menti volontairement",
    ],
    correct: [1],
    explanation: "Les gens disent « oui » facilement à une question hypothétique ; on valide par un comportement réel (test, pré-achat).",
    feedbackOnError: "Rappelez-vous l'écart entre ce que les gens disent et ce qu'ils font.",
    tags: ["déclaratif", "comportement", "validation"],
    editorialStatus: "approved",
  },
  // Segmentation (C6) : q06–q09
  {
    id: "mkt-v2-m2-q06",
    module: 2,
    week: 5,
    objectiveRef: "C6",
    difficulty: "easy",
    type: "mcq",
    prompt: "Quel est le principal défaut d'un segment défini comme « femmes de 25 à 45 ans » ?",
    options: [
      "Il est trop précis",
      "Il n'est pas actionnable : il mélange des besoins, budgets et modes de vie très différents",
      "Il est illégal",
      "Il est trop petit",
    ],
    correct: [1],
    explanation: "Un simple découpage démographique large n'est pas actionnable ; il faut combiner d'autres critères.",
    feedbackOnError: "Un bon segment est actionnable : on peut lui proposer un message et une offre spécifiques.",
    tags: ["segmentation", "actionnable"],
    editorialStatus: "approved",
  },
  {
    id: "mkt-v2-m2-q07",
    module: 2,
    week: 5,
    objectiveRef: "C6",
    difficulty: "medium",
    type: "multi",
    prompt: "Quels critères parmi les suivants relèvent de la segmentation ? (plusieurs réponses)",
    options: ["Psychographique (valeurs, mode de vie)", "Comportementale (fréquence d'achat)", "Le logo de l'entreprise", "Technographique (appareils, plateformes)"],
    correct: [0, 1, 3],
    explanation: "Psychographique, comportementale et technographique sont des critères de segmentation ; le logo n'en est pas un.",
    feedbackOnError: "La segmentation combine des critères sur les clients, pas sur la marque.",
    tags: ["segmentation", "critères"],
    editorialStatus: "approved",
  },
  {
    id: "mkt-v2-m2-q08",
    module: 2,
    week: 5,
    objectiveRef: "C6",
    difficulty: "medium",
    type: "mcq",
    prompt: "Quelles sont les quatre qualités d'un bon segment ?",
    options: [
      "Mesurable, accessible, substantiel, actionnable",
      "Grand, ancien, connu, populaire",
      "Gratuit, rapide, local, tendance",
      "Jeune, urbain, connecté, riche",
    ],
    correct: [0],
    explanation: "Un segment utile est mesurable, accessible, substantiel (assez gros) et actionnable.",
    feedbackOnError: "Rappelez-vous les 4 qualités : mesurable, accessible, substantiel, actionnable.",
    tags: ["segmentation", "qualité"],
    editorialStatus: "approved",
  },
  {
    id: "mkt-v2-m2-q09",
    module: 2,
    week: 5,
    objectiveRef: "C6",
    difficulty: "hard",
    type: "scenario",
    prompt:
      "Un studio de photo peut servir familles, PME et mariages. Avec un budget limité, quel principe doit guider le choix du segment cible ?",
    options: [
      "Choisir le plus grand segment quoi qu'il arrive",
      "Choisir le segment le plus attractif ET que l'on a la meilleure capacité à servir",
      "Servir les trois en même temps",
      "Choisir au hasard",
    ],
    correct: [1],
    explanation: "La cible est le segment où l'on peut gagner : attractivité croisée avec la capacité à le servir.",
    feedbackOnError: "La cible n'est pas le plus gros segment, mais celui où l'on a les meilleures chances.",
    tags: ["segmentation", "priorisation"],
    editorialStatus: "approved",
  },
  // Personas & JTBD (C6) : q10–q12
  {
    id: "mkt-v2-m2-q10",
    module: 2,
    week: 5,
    objectiveRef: "C6",
    difficulty: "medium",
    type: "mcq",
    prompt: "Qu'est-ce qui distingue un persona d'un stéréotype ?",
    options: [
      "Le persona a une photo",
      "Le persona est fondé sur des données réelles, le stéréotype sur des préjugés non vérifiés",
      "Le persona est toujours plus jeune",
      "Il n'y a aucune différence",
    ],
    correct: [1],
    explanation: "La différence tient à la source : données vérifiées (persona) vs suppositions (stéréotype).",
    feedbackOnError: "Un persona s'appuie sur des faits ; un stéréotype sur des préjugés.",
    tags: ["persona", "stéréotype"],
    editorialStatus: "approved",
  },
  {
    id: "mkt-v2-m2-q11",
    module: 2,
    week: 5,
    objectiveRef: "C6",
    difficulty: "medium",
    type: "analysis",
    prompt:
      "Dans une fiche persona, vous ajoutez « salaire exact de 62 400 $ » sans aucune donnée à l'appui. Pourquoi est-ce problématique ?",
    options: [
      "C'est trop précis pour être utile",
      "Cela crée une fausse précision qui trompe l'équipe ; mieux vaut une fourchette honnête ou une hypothèse marquée",
      "Les salaires ne doivent jamais figurer",
      "Ce n'est pas problématique",
    ],
    correct: [1],
    explanation: "Inventer des chiffres précis donne une illusion de rigueur ; on marque les hypothèses ou on donne une fourchette.",
    feedbackOnError: "Évitez la fausse précision : distinguez données et hypothèses.",
    tags: ["persona", "fausse-précision"],
    editorialStatus: "approved",
  },
  {
    id: "mkt-v2-m2-q12",
    module: 2,
    week: 5,
    objectiveRef: "C6",
    difficulty: "medium",
    type: "mcq",
    prompt: "Dans l'approche Jobs-to-be-Done, que signifie le « travail émotionnel » ?",
    options: [
      "La tâche concrète à accomplir",
      "Ce que le client veut ressentir (sécurité, fierté, sérénité)",
      "L'image projetée auprès des autres",
      "Le prix du produit",
    ],
    correct: [1],
    explanation: "Le travail émotionnel est le ressenti visé ; le fonctionnel est la tâche, le social est l'image projetée.",
    feedbackOnError: "Fonctionnel = tâche ; émotionnel = ressenti ; social = image.",
    tags: ["JTBD", "besoins"],
    editorialStatus: "approved",
  },
  // Concurrence (C7) : q13–q15
  {
    id: "mkt-v2-m2-q13",
    module: 2,
    week: 6,
    objectiveRef: "C7",
    difficulty: "easy",
    type: "mcq",
    prompt: "Un concurrent INDIRECT est :",
    options: [
      "Une entreprise offrant exactement le même produit",
      "Une solution différente qui répond au même besoin (job) du client",
      "Un fournisseur",
      "Un client insatisfait",
    ],
    correct: [1],
    explanation: "Le concurrent indirect résout le même job autrement ; le direct offre une solution similaire.",
    feedbackOnError: "Pensez « même besoin, solution différente » pour l'indirect.",
    tags: ["concurrence", "indirect"],
    editorialStatus: "approved",
  },
  {
    id: "mkt-v2-m2-q14",
    module: 2,
    week: 6,
    objectiveRef: "C7",
    difficulty: "medium",
    type: "scenario",
    prompt:
      "Les ventes matinales d'un café baissent alors que ses deux concurrents directs sont stables. Qu'a-t-il probablement négligé ?",
    options: [
      "Ses concurrents directs",
      "Les concurrents indirects et substituts (dépanneur à 1 $, café maison en télétravail)",
      "Son logo",
      "Le prix de ses grains",
    ],
    correct: [1],
    explanation: "La vraie concurrence incluait des indirects et des substituts hors du radar habituel.",
    feedbackOnError: "N'oubliez pas les concurrents indirects et les solutions de substitution.",
    tags: ["concurrence", "substituts"],
    editorialStatus: "approved",
  },
  {
    id: "mkt-v2-m2-q15",
    module: 2,
    week: 6,
    objectiveRef: "C7",
    difficulty: "medium",
    type: "mcq",
    prompt: "Qu'est-ce qu'un benchmark éthique ?",
    options: [
      "Copier secrètement les fichiers internes d'un concurrent",
      "Comparer à partir d'informations publiques et légitimes (sites, avis, tarifs affichés)",
      "Se faire passer pour un client pour obtenir des données privées",
      "Diffuser de fausses informations sur un concurrent",
    ],
    correct: [1],
    explanation: "Le benchmark éthique s'appuie sur des informations publiques, sans manœuvre trompeuse ni intrusion.",
    feedbackOnError: "Comparer à partir de sources publiques est éthique ; l'espionnage ne l'est pas.",
    tags: ["concurrence", "éthique"],
    editorialStatus: "approved",
  },
  // SWOT (C7) : q16–q17
  {
    id: "mkt-v2-m2-q16",
    module: 2,
    week: 6,
    objectiveRef: "C7",
    difficulty: "medium",
    type: "scenario",
    prompt: "Dans une SWOT, où classer « une nouvelle réglementation favorable au secteur » ?",
    options: ["Force (interne)", "Faiblesse (interne)", "Opportunité (externe)", "Menace (externe)"],
    correct: [2],
    explanation: "Une réglementation vient du marché/environnement : c'est un facteur externe favorable, donc une opportunité.",
    feedbackOnError: "Forces/faiblesses = interne ; opportunités/menaces = externe.",
    tags: ["SWOT", "interne-externe"],
    editorialStatus: "approved",
  },
  {
    id: "mkt-v2-m2-q17",
    module: 2,
    week: 6,
    objectiveRef: "C7",
    difficulty: "hard",
    type: "analysis",
    prompt: "Qu'est-ce qui rend une SWOT réellement utile plutôt qu'une simple liste ?",
    options: [
      "Avoir le plus d'éléments possible par case",
      "Des facteurs précis et étayés, priorisés, puis CROISÉS pour produire des décisions",
      "Utiliser de belles couleurs",
      "La remplir rapidement sans recherche",
    ],
    correct: [1],
    explanation: "La valeur vient du croisement (F×O, f×M…) qui transforme le constat en décisions, sur des faits priorisés.",
    feedbackOnError: "Une SWOT utile est précise, priorisée et croisée.",
    tags: ["SWOT", "croisement"],
    editorialStatus: "approved",
  },
  // Proposition de valeur & positionnement (C7) : q18–q20
  {
    id: "mkt-v2-m2-q18",
    module: 2,
    week: 6,
    objectiveRef: "C7",
    difficulty: "medium",
    type: "scenario",
    prompt: "Laquelle est la MEILLEURE proposition de valeur ?",
    options: [
      "« Des produits de qualité à prix imbattables »",
      "« La solution innovante pour votre bien-être »",
      "« Pour les parents pressés, nos repas prêts en 5 min sont approuvés par une nutritionniste, sans additifs »",
      "« Le meilleur choix du marché »",
    ],
    correct: [2],
    explanation: "Elle cible un segment précis, promet un bénéfice concret, apporte une preuve (nutritionniste) et une différence (sans additifs).",
    feedbackOnError: "Une bonne proposition est spécifique, prouvée et différenciante.",
    tags: ["proposition-valeur"],
    editorialStatus: "approved",
  },
  {
    id: "mkt-v2-m2-q19",
    module: 2,
    week: 6,
    objectiveRef: "C7",
    difficulty: "medium",
    type: "truefalse",
    prompt: "Vrai ou faux (raisonné) : « Une promesse marketing forte peut se passer de preuve tant qu'elle est bien formulée. »",
    options: [
      "Vrai — le style suffit à convaincre",
      "Faux — sans preuve (chiffre, garantie, témoignage), une promesse n'est qu'un slogan peu crédible",
      "Vrai — les clients ne vérifient jamais",
      "Faux — il ne faut jamais faire de promesse",
    ],
    correct: [1],
    explanation: "La preuve (raison de croire) rend la promesse crédible ; sans elle, ce n'est qu'un slogan.",
    feedbackOnError: "Une promesse sans preuve manque de crédibilité.",
    tags: ["proposition-valeur", "preuve"],
    editorialStatus: "approved",
  },
  {
    id: "mkt-v2-m2-q20",
    module: 2,
    week: 6,
    objectiveRef: "C7",
    difficulty: "hard",
    type: "scenario",
    prompt:
      "Une entreprise se positionne comme « la plateforme tout-en-un pour toutes les entreprises » et peine à vendre. Quelle correction est la plus solide ?",
    options: [
      "Baisser les prix",
      "Assumer un choix : cibler un segment précis avec une promesse et une différence claires",
      "Ajouter encore plus de fonctionnalités",
      "Changer de logo",
    ],
    correct: [1],
    explanation: "Un positionnement fort assume un choix (cible, promesse, différence) plutôt que de viser « tout le monde ».",
    feedbackOnError: "« Tout pour tous » n'occupe aucune place claire ; il faut assumer un choix.",
    tags: ["positionnement"],
    editorialStatus: "approved",
  },

  // ═══════════════════ MODULE 3 — 20 questions (semaines 7–9) ═══════════════════
  // Fondements de la marque (C8) : q01–q04
  {
    id: "mkt-v2-m3-q01",
    module: 3,
    week: 7,
    objectiveRef: "C8",
    difficulty: "easy",
    type: "mcq",
    prompt: "Qu'est-ce qu'une marque, fondamentalement ?",
    options: [
      "Le logo et la palette de couleurs d'une entreprise",
      "L'ensemble des perceptions et émotions qu'une personne associe à une entreprise, un produit ou un individu",
      "Le nom déposé d'un produit",
      "La publicité d'une entreprise",
    ],
    correct: [1],
    explanation: "La marque vit dans l'esprit du public : c'est une perception, pas un simple visuel.",
    feedbackOnError: "Le logo n'est qu'un signal ; la marque est la perception d'ensemble.",
    tags: ["marque", "définition"],
    editorialStatus: "approved",
  },
  {
    id: "mkt-v2-m3-q02",
    module: 3,
    week: 7,
    objectiveRef: "C8",
    difficulty: "medium",
    type: "truefalse",
    prompt: "Vrai ou faux (raisonné) : « Refaire le logo d'une entreprise suffit à transformer sa marque. »",
    options: [
      "Vrai — le logo est la marque",
      "Faux — la marque se construit par l'expérience et la cohérence, pas par le seul habillage visuel",
      "Vrai — les clients ne regardent que le logo",
      "Faux — il ne faut jamais changer de logo",
    ],
    correct: [1],
    explanation: "La marque se joue dans l'expérience répétée et la cohérence ; le logo n'en est qu'un signal.",
    feedbackOnError: "Distinguez identité visuelle (signal) et marque (perception).",
    tags: ["marque", "identité"],
    editorialStatus: "approved",
  },
  {
    id: "mkt-v2-m3-q03",
    module: 3,
    week: 7,
    objectiveRef: "C8",
    difficulty: "medium",
    type: "association",
    prompt:
      "Quelle association est correcte ? (identité visuelle / réputation / marque)",
    options: [
      "Avis clients = identité visuelle ; logo = réputation",
      "Logo et typographie = identité visuelle ; avis des clients = réputation ; perception globale = marque",
      "Perception globale = identité visuelle ; logo = marque",
      "Réputation = logo ; marque = palette de couleurs",
    ],
    correct: [1],
    explanation: "L'identité visuelle est un signal, la réputation vient des autres, la marque est la perception d'ensemble.",
    feedbackOnError: "Reliez chaque élément à sa bonne catégorie.",
    tags: ["marque", "réputation", "association"],
    editorialStatus: "approved",
  },
  {
    id: "mkt-v2-m3-q04",
    module: 3,
    week: 7,
    objectiveRef: "C8",
    difficulty: "medium",
    type: "mcq",
    prompt: "Qu'est-ce que le capital de marque ?",
    options: [
      "Le montant investi dans la publicité",
      "La valeur ajoutée par la marque au-delà du produit (notoriété, associations positives, fidélité, préférence)",
      "Le nombre d'abonnés sur les réseaux",
      "Le coût de création du logo",
    ],
    correct: [1],
    explanation: "Le capital de marque est la valeur que la marque ajoute au produit lui-même.",
    feedbackOnError: "Pensez à la préférence et à la fidélité qu'inspire une marque forte.",
    tags: ["capital-marque"],
    editorialStatus: "approved",
  },
  // Mission, vision, valeurs, promesse (C8) : q05–q07
  {
    id: "mkt-v2-m3-q05",
    module: 3,
    week: 7,
    objectiveRef: "C8",
    difficulty: "easy",
    type: "mcq",
    prompt: "Quelle affirmation décrit correctement la différence mission / vision ?",
    options: [
      "La mission décrit le futur souhaité ; la vision, l'action présente",
      "La mission décrit ce que la marque fait au présent ; la vision, le futur souhaité",
      "Mission et vision sont synonymes",
      "La vision est le slogan ; la mission, le logo",
    ],
    correct: [1],
    explanation: "Mission = présent (ce qu'on fait, pour qui) ; vision = futur souhaité.",
    feedbackOnError: "Mission au présent, vision tournée vers l'avenir.",
    tags: ["mission", "vision"],
    editorialStatus: "approved",
  },
  {
    id: "mkt-v2-m3-q06",
    module: 3,
    week: 7,
    objectiveRef: "C8",
    difficulty: "hard",
    type: "analysis",
    prompt:
      "Une mission affirme : « Offrir des produits de qualité et satisfaire nos clients. » Quel est son principal défaut ?",
    options: [
      "Elle est trop longue",
      "Elle est vague et interchangeable : n'importe quel concurrent pourrait la signer sans changer un mot",
      "Elle est trop spécifique",
      "Elle ne contient pas de chiffres",
    ],
    correct: [1],
    explanation: "Le test de spécificité : si un concurrent peut la reprendre telle quelle, la mission ne dit rien de distinctif.",
    feedbackOnError: "Une bonne mission est spécifique et distinctive.",
    tags: ["mission", "spécificité"],
    editorialStatus: "approved",
  },
  {
    id: "mkt-v2-m3-q07",
    module: 3,
    week: 7,
    objectiveRef: "C8",
    difficulty: "medium",
    type: "truefalse",
    prompt: "Vrai ou faux (raisonné) : « Afficher dix valeurs impressionnantes renforce toujours la marque. »",
    options: [
      "Vrai — plus il y a de valeurs, mieux c'est",
      "Faux — des valeurs affichées mais non vécues détruisent la confiance ; mieux vaut peu de valeurs réellement appliquées",
      "Vrai — les clients comptent les valeurs",
      "Faux — une marque ne doit avoir aucune valeur",
    ],
    correct: [1],
    explanation: "La cohérence discours/réalité prime : trois valeurs vécues valent mieux que dix décoratives.",
    feedbackOnError: "Une valeur non tenue nuit plus qu'elle n'aide.",
    tags: ["valeurs", "cohérence"],
    editorialStatus: "approved",
  },
  // Voix, ton, architecture de messages (C8/C9) : q08–q10
  {
    id: "mkt-v2-m3-q08",
    module: 3,
    week: 7,
    objectiveRef: "C9",
    difficulty: "medium",
    type: "mcq",
    prompt: "Quelle est la différence entre la voix et le ton d'une marque ?",
    options: [
      "La voix change à chaque publication ; le ton est fixe",
      "La voix est constante (personnalité en mots) ; le ton s'adapte au contexte",
      "Voix et ton sont identiques",
      "La voix est visuelle ; le ton est écrit",
    ],
    correct: [1],
    explanation: "La voix reste constante ; le ton s'ajuste au contexte et à l'émotion du lecteur.",
    feedbackOnError: "Voix = constante ; ton = contextuel.",
    tags: ["voix", "ton"],
    editorialStatus: "approved",
  },
  {
    id: "mkt-v2-m3-q09",
    module: 3,
    week: 7,
    objectiveRef: "C8",
    difficulty: "medium",
    type: "scenario",
    prompt:
      "Une marque à la voix « claire et bienveillante » répond à un client mécontent. Quel ton adopter sans trahir la voix ?",
    options: [
      "Un ton agressif pour se défendre",
      "Un ton empathique et responsable, tout en restant clair et bienveillant",
      "Un ton purement commercial qui propose une promotion",
      "Un ton ironique",
    ],
    correct: [1],
    explanation: "Le ton s'adapte (empathie face à un mécontentement) mais la voix (clarté, bienveillance) demeure.",
    feedbackOnError: "Même voix, ton ajusté à l'émotion du lecteur.",
    tags: ["ton", "service-client"],
    editorialStatus: "approved",
  },
  {
    id: "mkt-v2-m3-q10",
    module: 3,
    week: 7,
    objectiveRef: "C8",
    difficulty: "hard",
    type: "analysis",
    prompt: "Comment doit-on utiliser les archétypes de marque (le Sage, le Héros, etc.) ?",
    options: [
      "Comme des règles absolues à suivre à la lettre",
      "Comme des outils d'inspiration à adapter, jamais comme des cases rigides",
      "Comme des logos",
      "Comme des slogans obligatoires",
    ],
    correct: [1],
    explanation: "Les archétypes aident à incarner une personnalité ; ce sont des repères souples, pas des contraintes.",
    feedbackOnError: "Les archétypes sont des outils, pas des règles absolues.",
    tags: ["archétype", "personnalité"],
    editorialStatus: "approved",
  },
  // Stratégie de contenu (C9) : q11–q14
  {
    id: "mkt-v2-m3-q11",
    module: 3,
    week: 8,
    objectiveRef: "C9",
    difficulty: "easy",
    type: "mcq",
    prompt: "Quelle est la différence entre « publier » et « communiquer stratégiquement » ?",
    options: [
      "Aucune différence",
      "Publier = mettre du contenu en ligne ; communiquer stratégiquement = le bon contenu, pour le bon persona, à la bonne étape, avec un objectif mesurable",
      "Communiquer stratégiquement signifie publier plus souvent",
      "Publier coûte plus cher",
    ],
    correct: [1],
    explanation: "Sans cible ni objectif, publier n'est que du bruit ; la stratégie relie contenu, persona, étape et objectif.",
    feedbackOnError: "La stratégie ajoute cible, étape et objectif mesurable.",
    tags: ["contenu", "stratégie"],
    editorialStatus: "approved",
  },
  {
    id: "mkt-v2-m3-q12",
    module: 3,
    week: 8,
    objectiveRef: "C9",
    difficulty: "medium",
    type: "scenario",
    prompt:
      "Une marque ne publie que des promotions. Quel est le principal risque ?",
    options: [
      "Trop informer les clients",
      "Lasser l'audience et ne construire ni confiance ni relation, faute d'équilibre valeur/promotion",
      "Améliorer sa réputation",
      "Réduire ses ventes de logo",
    ],
    correct: [1],
    explanation: "Un flux uniquement promotionnel épuise l'audience ; il faut équilibrer valeur et promotion.",
    feedbackOnError: "Équilibrez contenu de valeur et contenu promotionnel.",
    tags: ["contenu", "équilibre"],
    editorialStatus: "approved",
  },
  {
    id: "mkt-v2-m3-q13",
    module: 3,
    week: 8,
    objectiveRef: "C9",
    difficulty: "medium",
    type: "mcq",
    prompt: "D'où doivent provenir les piliers éditoriaux ?",
    options: [
      "Des sujets qui plaisent à l'équipe",
      "Des besoins, questions et objections des personas, croisés avec l'expertise de la marque",
      "Des tendances virales du moment",
      "Du nombre de mots-clés disponibles",
    ],
    correct: [1],
    explanation: "Les piliers se dérivent des personas (Module 2) ; c'est ce qui rend le contenu pertinent.",
    feedbackOnError: "Chaque pilier doit répondre à un besoin identifié du persona.",
    tags: ["piliers", "personas"],
    editorialStatus: "approved",
  },
  {
    id: "mkt-v2-m3-q14",
    module: 3,
    week: 8,
    objectiveRef: "C9",
    difficulty: "hard",
    type: "scenario",
    prompt:
      "Le persona « nouvel arrivant cherchant un emploi qualifié » a pour besoin de comprendre le marché local. Quel pilier éditorial est le plus pertinent ?",
    options: [
      "« Nos réussites internes »",
      "« Comprendre le marché de l'emploi local (secteurs, équivalences, entrevues) »",
      "« Actualités générales du sport »",
      "« Promotions de la semaine »",
    ],
    correct: [1],
    explanation: "Le pilier doit répondre directement au besoin identifié du persona.",
    feedbackOnError: "Reliez le pilier au besoin réel du persona.",
    tags: ["piliers", "pertinence"],
    editorialStatus: "approved",
  },
  // Calendrier éditorial (C9) : q15–q16
  {
    id: "mkt-v2-m3-q15",
    module: 3,
    week: 8,
    objectiveRef: "C9",
    difficulty: "medium",
    type: "mcq",
    prompt: "Que signifie « réutiliser » (repurposing) un contenu ?",
    options: [
      "Copier-coller le même texte sur tous les canaux",
      "Décliner un contenu de fond en plusieurs formats adaptés à chaque canal, en gardant le message central",
      "Republier exactement le même contenu chaque semaine",
      "Supprimer les anciens contenus",
    ],
    correct: [1],
    explanation: "Réutiliser = « créer une fois, décliner souvent » en adaptant, pas dupliquer à l'identique.",
    feedbackOnError: "Réutiliser adapte le contenu ; ce n'est pas du copier-coller.",
    tags: ["réutilisation", "formats"],
    editorialStatus: "approved",
  },
  {
    id: "mkt-v2-m3-q16",
    module: 3,
    week: 8,
    objectiveRef: "C9",
    difficulty: "medium",
    type: "truefalse",
    prompt:
      "Vrai ou faux (raisonné) : « Un contenu peut être publié dès qu'il est prêt, sans étape de validation. »",
    options: [
      "Vrai — la rapidité prime",
      "Faux — un statut « validé » (relecture) est un garde-fou contre erreurs, promesses trompeuses et données non vérifiées",
      "Vrai — la validation ralentit inutilement",
      "Faux — il ne faut jamais publier",
    ],
    correct: [1],
    explanation: "La gouvernance éditoriale impose une validation avant publication.",
    feedbackOnError: "Rien ne se publie sans relecture/validation.",
    tags: ["calendrier", "gouvernance"],
    editorialStatus: "approved",
  },
  // Copywriting & storytelling (C10) : q17–q18
  {
    id: "mkt-v2-m3-q17",
    module: 3,
    week: 9,
    objectiveRef: "C10",
    difficulty: "medium",
    type: "analysis",
    prompt: "Laquelle de ces accroches constitue une surpromesse à éviter ?",
    options: [
      "« Émettez vos factures en 2 minutes — essai 14 jours, sans carte »",
      "« Devenez riche et obtenez un emploi garanti grâce à notre formation »",
      "« Un guide clair pour éviter 5 erreurs courantes »",
      "« Satisfait ou remboursé sous 30 jours »",
    ],
    correct: [1],
    explanation: "« Devenez riche » et « emploi garanti » sont des surpromesses trompeuses et non conformes.",
    feedbackOnError: "Aucune promesse de revenu ou d'emploi garanti.",
    tags: ["copywriting", "éthique"],
    editorialStatus: "approved",
  },
  {
    id: "mkt-v2-m3-q18",
    module: 3,
    week: 9,
    objectiveRef: "C10",
    difficulty: "medium",
    type: "mcq",
    prompt: "Dans un storytelling de marque efficace, qui est le héros ?",
    options: [
      "La marque, qui montre sa grandeur",
      "Le client, la marque jouant le rôle de guide qui l'aide à réussir",
      "Le concurrent",
      "Le fournisseur",
    ],
    correct: [1],
    explanation: "Le client est le protagoniste ; la marque est le guide. Le lecteur se reconnaît dans le héros.",
    feedbackOnError: "Client héros, marque guide.",
    tags: ["storytelling"],
    editorialStatus: "approved",
  },
  // IA responsable (C10) : q19–q20
  {
    id: "mkt-v2-m3-q19",
    module: 3,
    week: 9,
    objectiveRef: "C10",
    difficulty: "medium",
    type: "mcq",
    prompt: "Qu'est-ce qu'une « hallucination » d'IA en production de contenu ?",
    options: [
      "Une image générée",
      "Un contenu faux (faits, chiffres ou sources inventés) présenté avec assurance",
      "Une faute d'orthographe",
      "Un contenu trop long",
    ],
    correct: [1],
    explanation: "L'IA peut inventer des faits/sources plausibles mais faux : d'où la vérification humaine obligatoire.",
    feedbackOnError: "Vérifiez chaque fait et chaque source d'une sortie d'IA.",
    tags: ["ia", "hallucination"],
    editorialStatus: "approved",
  },
  {
    id: "mkt-v2-m3-q20",
    module: 3,
    week: 9,
    objectiveRef: "C10",
    difficulty: "hard",
    type: "scenario",
    prompt:
      "Une IA génère une fiche produit affirmant « guérit l'anxiété, 89 % de clients satisfaits (source interne non publiée) ». Que faire avant publication ?",
    options: [
      "Publier tel quel, l'IA est fiable",
      "Rejeter/corriger : allégation santé non conforme, statistique non vérifiable — contrôle humain et vérification des faits obligatoires",
      "Ajouter plus de chiffres impressionnants",
      "Publier en ajoutant un emoji",
    ],
    correct: [1],
    explanation: "Contrôle humain systématique : allégations santé et chiffres non vérifiables sont retirés ou corrigés.",
    feedbackOnError: "L'IA produit un brouillon à vérifier, jamais une publication automatique.",
    tags: ["ia", "conformité", "contrôle-éditorial"],
    editorialStatus: "approved",
  },

  // ═══════════════════ MODULE 4 — 20 questions (semaines 10–12) ═══════════════════
  // Acquisition & canaux (C11) : q01–q03
  {
    id: "mkt-v2-m4-q01",
    module: 4,
    week: 10,
    objectiveRef: "C11",
    difficulty: "easy",
    type: "mcq",
    prompt: "Dans le cadre médias détenus / gagnés / payants, qu'est-ce qu'un média « détenu » ?",
    options: [
      "Une annonce payée sur un réseau social",
      "Un canal que vous possédez (site, liste de courriels), actif durable",
      "Une mention spontanée par un tiers",
      "Un article sponsorisé",
    ],
    correct: [1],
    explanation: "Les médias détenus (site, liste courriel) vous appartiennent et constituent un actif durable.",
    feedbackOnError: "Détenu = possédé ; gagné = offert par un tiers ; payant = loué.",
    tags: ["acquisition", "médias"],
    editorialStatus: "approved",
  },
  {
    id: "mkt-v2-m4-q02",
    module: 4,
    week: 10,
    objectiveRef: "C11",
    difficulty: "medium",
    type: "truefalse",
    prompt: "Vrai ou faux (raisonné) : « Une entreprise peut sereinement dépendre uniquement de la publicité payante. »",
    options: [
      "Vrai — la publicité suffit toujours",
      "Faux — la dépendance à la seule publicité est fragile (hausse des coûts, suspensions) ; il faut aussi des actifs détenus et de la confiance",
      "Vrai — les actifs détenus sont inutiles",
      "Faux — il ne faut jamais faire de publicité",
    ],
    correct: [1],
    explanation: "La publicité est un accélérateur, pas une fondation ; on bâtit des médias détenus et gagnés.",
    feedbackOnError: "Diversifier réduit la dépendance et le coût d'acquisition dans le temps.",
    tags: ["acquisition", "durabilité"],
    editorialStatus: "approved",
  },
  {
    id: "mkt-v2-m4-q03",
    module: 4,
    week: 10,
    objectiveRef: "C11",
    difficulty: "medium",
    type: "scenario",
    prompt:
      "Un persona B2B (décideur, cycle long) doit être atteint. Quel canal est le plus cohérent ?",
    options: [
      "Un réseau de vidéos courtes de divertissement",
      "Une plateforme professionnelle avec contenu et ciblage B2B",
      "Une affiche de rue",
      "Un jeu mobile",
    ],
    correct: [1],
    explanation: "Le canal doit correspondre aux habitudes du persona et au cycle de vente.",
    feedbackOnError: "Le bon canal suit le persona, pas la mode.",
    tags: ["acquisition", "canal", "persona"],
    editorialStatus: "approved",
  },
  // Entonnoir & parcours (C11) : q04–q06
  {
    id: "mkt-v2-m4-q04",
    module: 4,
    week: 10,
    objectiveRef: "C11",
    difficulty: "medium",
    type: "mcq",
    prompt: "Quelle est la différence entre microconversion et macroconversion ?",
    options: [
      "La macroconversion est un petit pas, la micro l'objectif final",
      "La macroconversion est l'objectif principal (achat) ; la microconversion est un petit pas qui y mène (téléchargement, ajout au panier)",
      "Elles sont identiques",
      "La microconversion ne se mesure pas",
    ],
    correct: [1],
    explanation: "Les microconversions (petits pas) mènent à la macroconversion (objectif principal).",
    feedbackOnError: "Micro = petit pas mesurable ; macro = objectif principal.",
    tags: ["entonnoir", "conversion"],
    editorialStatus: "approved",
  },
  {
    id: "mkt-v2-m4-q05",
    module: 4,
    week: 10,
    objectiveRef: "C11",
    difficulty: "hard",
    type: "interpret",
    prompt:
      "Jeu de données pédagogique fictif : 1000 visiteurs → 400 vues produit → 350 ajouts panier → 60 achats. Où est la principale fuite ?",
    options: [
      "Entre visiteurs et vues produit",
      "Entre ajout au panier et achat (~83 % d'abandon au paiement)",
      "Entre vues produit et ajout panier",
      "Il n'y a pas de fuite",
    ],
    correct: [1],
    explanation: "La plus forte chute (350 → 60) situe la fuite au paiement.",
    feedbackOnError: "On compare le taux de passage entre étapes ; la plus forte chute est la priorité.",
    tags: ["entonnoir", "diagnostic"],
    editorialStatus: "approved",
  },
  {
    id: "mkt-v2-m4-q06",
    module: 4,
    week: 10,
    objectiveRef: "C11",
    difficulty: "medium",
    type: "analysis",
    prompt:
      "Une annonce promet « essai gratuit 30 jours » mais la page ne parle que d'un « achat immédiat ». Quel est le problème ?",
    options: [
      "Aucun problème",
      "Une rupture de cohérence annonce-page qui provoque l'abandon",
      "La page est trop rapide",
      "L'annonce est trop honnête",
    ],
    correct: [1],
    explanation: "L'incohérence entre l'annonce et la page casse la confiance et fait fuir le visiteur.",
    feedbackOnError: "La page doit tenir exactement la promesse de l'annonce.",
    tags: ["parcours", "cohérence"],
    editorialStatus: "approved",
  },
  // Objectifs & offres (C11) : q07–q09
  {
    id: "mkt-v2-m4-q07",
    module: 4,
    week: 10,
    objectiveRef: "C11",
    difficulty: "easy",
    type: "mcq",
    prompt: "Qu'est-ce qu'un aimant à prospects (lead magnet) ?",
    options: [
      "Une publicité payante",
      "Un avantage gratuit (guide, checklist, démo) échangé contre un contact",
      "Le prix le plus bas du marché",
      "Un logo attractif",
    ],
    correct: [1],
    explanation: "L'aimant à prospects échange une valeur gratuite contre un moyen de contact.",
    feedbackOnError: "C'est une première marche à faible risque pour entrer en relation.",
    tags: ["offre", "lead-magnet"],
    editorialStatus: "approved",
  },
  {
    id: "mkt-v2-m4-q08",
    module: 4,
    week: 10,
    objectiveRef: "C11",
    difficulty: "medium",
    type: "scenario",
    prompt:
      "Le but commercial est d'obtenir des essais qualifiés. Quel objectif publicitaire choisir ?",
    options: [
      "Maximiser les impressions",
      "Maximiser les conversions / prospects (aligné sur l'obtention d'essais)",
      "Maximiser la fréquence",
      "Maximiser les « j'aime »",
    ],
    correct: [1],
    explanation: "L'objectif publicitaire doit refléter le résultat commercial (essais), pas la simple visibilité.",
    feedbackOnError: "Aligner l'objectif publicitaire sur le but commercial.",
    tags: ["objectif", "alignement"],
    editorialStatus: "approved",
  },
  {
    id: "mkt-v2-m4-q09",
    module: 4,
    week: 10,
    objectiveRef: "C11",
    difficulty: "medium",
    type: "truefalse",
    prompt:
      "Vrai ou faux (raisonné) : « Un compte à rebours qui redémarre en boucle est une bonne technique d'urgence. »",
    options: [
      "Vrai — cela augmente les ventes",
      "Faux — c'est une fausse urgence trompeuse et interdite ; l'urgence doit être réelle",
      "Vrai — tout le monde le fait",
      "Faux — il ne faut jamais créer d'urgence",
    ],
    correct: [1],
    explanation: "La fausse urgence est trompeuse ; seule une urgence/rareté réelle est acceptable.",
    feedbackOnError: "Aucune fausse urgence ni fausse rareté.",
    tags: ["offre", "éthique"],
    editorialStatus: "approved",
  },
  // Plateformes publicitaires (C12) : q10–q12
  {
    id: "mkt-v2-m4-q10",
    module: 4,
    week: 11,
    objectiveRef: "C12",
    difficulty: "medium",
    type: "mcq",
    prompt: "Quelle est la hiérarchie typique d'une campagne publicitaire ?",
    options: [
      "Annonce → ensemble → campagne → compte",
      "Compte → campagne → ensemble de publicités → annonce",
      "Campagne → compte → annonce → ensemble",
      "Compte → annonce → campagne → ensemble",
    ],
    correct: [1],
    explanation: "Compte → campagne (objectif) → ensemble (audience/budget) → annonce (création).",
    feedbackOnError: "Retenez : compte, campagne, ensemble, annonce.",
    tags: ["plateformes", "structure"],
    editorialStatus: "approved",
  },
  {
    id: "mkt-v2-m4-q11",
    module: 4,
    week: 11,
    objectiveRef: "C12",
    difficulty: "hard",
    type: "analysis",
    prompt: "Quelle est la différence clé entre publicité sur moteur de recherche et sur réseau social ?",
    options: [
      "Aucune différence",
      "La recherche répond à une intention exprimée ; le réseau social interrompt un contenu et doit d'abord capter l'attention",
      "Le réseau social est toujours moins cher",
      "La recherche ne permet aucun ciblage",
    ],
    correct: [1],
    explanation: "Intention (recherche) vs interruption (social) change l'angle créatif et l'étape visée.",
    feedbackOnError: "Recherche = intention ; social = interruption.",
    tags: ["plateformes", "intention"],
    editorialStatus: "approved",
  },
  {
    id: "mkt-v2-m4-q12",
    module: 4,
    week: 11,
    objectiveRef: "C12",
    difficulty: "medium",
    type: "scenario",
    prompt:
      "Une campagne est modifiée (budget, audience, création) toutes les 12 heures. Quel est le risque ?",
    options: [
      "Aucun, c'est optimal",
      "Réinitialiser sans cesse la phase d'apprentissage et gaspiller le budget",
      "Améliorer immédiatement le ROAS",
      "Réduire les impressions à zéro définitivement",
    ],
    correct: [1],
    explanation: "Changer trop souvent perturbe l'apprentissage algorithmique et gaspille le budget.",
    feedbackOnError: "On laisse la phase d'apprentissage se stabiliser avant de juger.",
    tags: ["plateformes", "apprentissage"],
    editorialStatus: "approved",
  },
  // Audiences & ciblage (C12) : q13–q14
  {
    id: "mkt-v2-m4-q13",
    module: 4,
    week: 11,
    objectiveRef: "C12",
    difficulty: "medium",
    type: "association",
    prompt: "Quelle association température ↔ audience est correcte ?",
    options: [
      "Froide = a abandonné un panier ; chaude = ne connaît pas la marque",
      "Froide = ne connaît pas la marque ; tiède = a déjà interagi ; chaude = a montré une intention (panier, formulaire)",
      "Tiède = client fidèle ; chaude = inconnu",
      "Froide = abonné engagé ; chaude = inconnu",
    ],
    correct: [1],
    explanation: "Plus l'interaction et l'intention sont fortes, plus l'audience est chaude.",
    feedbackOnError: "Froide (inconnue) → tiède (a interagi) → chaude (intention forte).",
    tags: ["audiences", "température"],
    editorialStatus: "approved",
  },
  {
    id: "mkt-v2-m4-q14",
    module: 4,
    week: 11,
    objectiveRef: "C12",
    difficulty: "medium",
    type: "scenario",
    prompt:
      "Une campagne d'acquisition cible aussi les clients déjà abonnés et affiche l'annonce 15 fois/personne/semaine. Que corriger ?",
    options: [
      "Rien",
      "Exclure les clients déjà abonnés et réduire la fréquence (fatigue publicitaire)",
      "Augmenter encore la fréquence",
      "Supprimer tout ciblage",
    ],
    correct: [1],
    explanation: "Exclusions pertinentes + fréquence maîtrisée améliorent le rendement et évitent la fatigue.",
    feedbackOnError: "Exclure le non-pertinent et limiter la fréquence.",
    tags: ["audiences", "exclusions"],
    editorialStatus: "approved",
  },
  // Budget & enchères (C12) : q15–q16
  {
    id: "mkt-v2-m4-q15",
    module: 4,
    week: 11,
    objectiveRef: "C12",
    difficulty: "hard",
    type: "calc",
    prompt:
      "Jeu de données pédagogique fictif : marge de 30 $ par vente (achat unique). Quel est le CPA maximal acceptable au seuil de rentabilité ?",
    options: ["15 $", "30 $", "60 $", "10 $"],
    correct: [1],
    explanation: "Au seuil, CPA max = marge disponible par vente = 30 $ (hors valeur vie client).",
    feedbackOnError: "CPA max au seuil = marge par vente.",
    tags: ["budget", "CPA", "calcul"],
    editorialStatus: "approved",
  },
  {
    id: "mkt-v2-m4-q16",
    module: 4,
    week: 11,
    objectiveRef: "C12",
    difficulty: "medium",
    type: "mcq",
    prompt: "Quelle est la bonne approche pour engager un budget publicitaire ?",
    options: [
      "Miser un gros budget d'emblée sur une seule hypothèse",
      "Tester petit pour valider une hypothèse, puis amplifier progressivement ce qui est rentable",
      "Ne jamais tester",
      "Changer d'audience toutes les heures",
    ],
    correct: [1],
    explanation: "Tester petit avant d'amplifier protège le budget et l'apprentissage.",
    feedbackOnError: "Test → mesure → amplification progressive.",
    tags: ["budget", "test"],
    editorialStatus: "approved",
  },
  // Indicateurs & calculs (C13) : q17–q18
  {
    id: "mkt-v2-m4-q17",
    module: 4,
    week: 12,
    objectiveRef: "C13",
    difficulty: "medium",
    type: "calc",
    prompt:
      "Jeu de données pédagogique fictif : 8000 impressions, 160 clics, 240 $ dépensés. Quels sont le CTR et le CPC ?",
    options: [
      "CTR 2 % ; CPC 1,50 $",
      "CTR 5 % ; CPC 2 $",
      "CTR 1 % ; CPC 1,50 $",
      "CTR 2 % ; CPC 0,66 $",
    ],
    correct: [0],
    explanation: "CTR = 160/8000 × 100 = 2 % ; CPC = 240/160 = 1,50 $.",
    feedbackOnError: "CTR = clics/impressions × 100 ; CPC = dépenses/clics.",
    tags: ["indicateurs", "calcul"],
    editorialStatus: "approved",
  },
  {
    id: "mkt-v2-m4-q18",
    module: 4,
    week: 12,
    objectiveRef: "C13",
    difficulty: "hard",
    type: "interpret",
    prompt:
      "Jeu de données pédagogique fictif : Campagne A — CPA 12 $, marge 30 $ ; Campagne B — 5000 clics, CPA 45 $, marge 30 $. Laquelle est rentable ?",
    options: [
      "Campagne B, grâce à ses clics",
      "Campagne A (CPA 12 $ < marge 30 $) ; B perd de l'argent (CPA 45 $ > 30 $)",
      "Les deux",
      "Aucune",
    ],
    correct: [1],
    explanation: "On compare le CPA à la marge (CPA maximal acceptable), pas le volume de clics.",
    feedbackOnError: "Le nombre de clics est une vanité ; la rentabilité dépend du CPA vs marge.",
    tags: ["indicateurs", "rentabilité", "vanité"],
    editorialStatus: "approved",
  },
  // Conversion & page (C13) : q19
  {
    id: "mkt-v2-m4-q19",
    module: 4,
    week: 12,
    objectiveRef: "C13",
    difficulty: "medium",
    type: "mcq",
    prompt: "Quel principe augmente le plus fiablement le taux de conversion d'une page de destination ?",
    options: [
      "Multiplier les objectifs et les liens",
      "Un objectif unique, sans distraction, avec preuve et CTA clair, cohérent avec l'annonce",
      "Ajouter un menu de navigation complet",
      "Allonger le formulaire",
    ],
    correct: [1],
    explanation: "Objectif unique + suppression des distractions + preuve + cohérence annonce-page améliorent la conversion.",
    feedbackOnError: "Une page qui vise une seule action convertit mieux.",
    tags: ["conversion", "page"],
    editorialStatus: "approved",
  },
  // Attribution / test / conformité (C13) : q20
  {
    id: "mkt-v2-m4-q20",
    module: 4,
    week: 12,
    objectiveRef: "C13",
    difficulty: "hard",
    type: "analysis",
    prompt:
      "Pour un test A/B fiable sur une page, quelle démarche est correcte ?",
    options: [
      "Changer titre, image et CTA en même temps et conclure après 20 visites",
      "Ne changer qu'UNE variable, sur un volume et une durée suffisants, avec un groupe témoin, puis interpréter prudemment",
      "Choisir le gagnant au hasard",
      "Ne jamais tester",
    ],
    correct: [1],
    explanation: "Une variable unique, un échantillon suffisant et de la prudence évitent les faux gagnants.",
    feedbackOnError: "Un test fiable isole une seule variable sur assez de données.",
    tags: ["test-ab", "attribution", "rigueur"],
    editorialStatus: "approved",
  },
];
