import type { BankQuestion } from "@/lib/academic/types";

/**
 * Banque de questions — Marketing Digital v2.
 * ÉTAT : Module 1 rédigé comme exemplaire de référence (20 questions, difficulté et types variés).
 * Modules 2–8 : à rédiger module par module (voir MARKETING_QUESTION_BANK_AUDIT.md).
 *
 * SÉCURITÉ : `correct` ne doit jamais transiter vers le client public — la correction est serveur.
 */
export const marketingDigitalV2Bank: BankQuestion[] = [
  {
    id: "mkt-v2-m1-q01",
    module: 1,
    week: 1,
    objectiveRef: "C1",
    difficulty: "easy",
    type: "mcq",
    prompt: "Qu'est-ce qui distingue fondamentalement le marketing digital du marketing traditionnel ?",
    options: [
      "Il est toujours moins cher",
      "Il permet de mesurer précisément chaque interaction et d'ajuster en temps réel",
      "Il ne nécessite aucune stratégie",
      "Il touche uniquement les jeunes",
    ],
    correct: [1],
    explanation:
      "La mesurabilité et l'agilité (ajustement en temps réel) sont les traits distinctifs, pas le coût ni l'audience.",
    feedbackOnError: "Revoyez la notion de mesurabilité : chaque impression, clic et achat est traçable.",
    tags: ["fondamentaux", "définition"],
    editorialStatus: "approved",
  },
  {
    id: "mkt-v2-m1-q02",
    module: 1,
    week: 1,
    objectiveRef: "C1",
    difficulty: "easy",
    type: "mcq",
    prompt: "Dans le modèle AARRR, que signifie la première lettre « A » ?",
    options: ["Analytics", "Acquisition", "Activation", "Ads"],
    correct: [1],
    explanation: "AARRR = Acquisition, Activation, Rétention, Recommandation, Revenu.",
    feedbackOnError: "La première étape attire du trafic : c'est l'Acquisition.",
    tags: ["funnel", "AARRR"],
    editorialStatus: "approved",
  },
  {
    id: "mkt-v2-m1-q03",
    module: 1,
    week: 1,
    objectiveRef: "C2",
    difficulty: "medium",
    type: "multi",
    prompt: "Parmi les éléments suivants, lesquels appartiennent au modèle AARRR ? (plusieurs réponses)",
    options: ["Rétention", "Recommandation", "Rentabilité brute", "Activation"],
    correct: [0, 1, 3],
    explanation: "AARRR contient Rétention, Recommandation et Activation ; « Rentabilité brute » n'en fait pas partie.",
    feedbackOnError: "Rappelez-vous : Acquisition, Activation, Rétention, Recommandation, Revenu.",
    tags: ["funnel", "AARRR"],
    editorialStatus: "approved",
  },
  {
    id: "mkt-v2-m1-q04",
    module: 1,
    week: 2,
    objectiveRef: "C2",
    difficulty: "medium",
    type: "scenario",
    prompt:
      "Une boutique attire 5 000 visiteurs/mois mais 93 % quittent la fiche produit sans rien ajouter au panier. Où se situe la fuite du funnel ?",
    options: ["Acquisition", "Activation", "Recommandation", "Revenu"],
    correct: [1],
    explanation:
      "Le trafic arrive (Acquisition OK) mais la conversion échoue : la fuite est à l'Activation. Augmenter le budget pub n'y changerait rien.",
    feedbackOnError: "Le trafic est bon ; le problème est la conversion des visiteurs en action.",
    tags: ["funnel", "diagnostic"],
    editorialStatus: "approved",
  },
  {
    id: "mkt-v2-m1-q05",
    module: 1,
    week: 2,
    objectiveRef: "C3",
    difficulty: "medium",
    type: "mcq",
    prompt: "Qu'est-ce qu'un persona en marketing ?",
    options: [
      "Le nom commercial d'un produit",
      "La représentation semi-fictive du client idéal (habitudes, freins, canaux)",
      "Un influenceur payé",
      "Le logo d'une marque",
    ],
    correct: [1],
    explanation: "Le persona synthétise le client idéal pour guider le choix des messages et des canaux.",
    feedbackOnError: "Un persona décrit un type de client, pas un produit ni une marque.",
    tags: ["persona", "ciblage"],
    editorialStatus: "approved",
  },
  {
    id: "mkt-v2-m1-q06",
    module: 1,
    week: 2,
    objectiveRef: "C3",
    difficulty: "hard",
    type: "scenario",
    prompt:
      "Un logiciel B2B à cycle de vente de 4 mois avec plusieurs décideurs. Quelle approche est la plus cohérente ?",
    options: [
      "Une campagne d'achat impulsif sur TikTok",
      "Un contenu éducatif et un nurturing par email/LinkedIn adapté au cycle long",
      "Des soldes flash quotidiennes",
      "Uniquement des publicités display génériques",
    ],
    correct: [1],
    explanation:
      "Un cycle B2B long et multi-décideurs se travaille par contenu de fond et nurturing, pas par l'impulsion.",
    feedbackOnError: "Adaptez le canal et le message au cycle de vente et au persona, pas à la mode.",
    tags: ["persona", "B2B", "canaux"],
    editorialStatus: "approved",
  },
  {
    id: "mkt-v2-m1-q07",
    module: 1,
    week: 1,
    objectiveRef: "C2",
    difficulty: "easy",
    type: "mcq",
    prompt: "Pourquoi attirer davantage de trafic est-il inutile si le site ne convertit pas ?",
    options: [
      "Parce que le trafic coûte cher",
      "Parce que la fuite du funnel est en aval : plus de visiteurs = plus de pertes au même endroit",
      "Parce que Google le pénalise",
      "Parce que le trafic ralentit le site",
    ],
    correct: [1],
    explanation: "On corrige d'abord l'étape qui fuit ; sinon on amplifie simplement la perte.",
    feedbackOnError: "Identifiez l'étape qui fuit avant d'investir en amont.",
    tags: ["funnel", "priorisation"],
    editorialStatus: "approved",
  },
  {
    id: "mkt-v2-m1-q08",
    module: 1,
    week: 3,
    objectiveRef: "C4",
    difficulty: "medium",
    type: "calc",
    prompt:
      "Une campagne coûte 800 $ et génère 40 nouveaux clients. Quel est le coût d'acquisition client (CAC) ?",
    options: ["20 $", "32 $", "40 $", "80 $"],
    correct: [0],
    explanation: "CAC = dépense / clients acquis = 800 / 40 = 20 $.",
    feedbackOnError: "CAC = coût total ÷ nombre de clients acquis.",
    tags: ["CAC", "calcul"],
    editorialStatus: "approved",
  },
  {
    id: "mkt-v2-m1-q09",
    module: 1,
    week: 3,
    objectiveRef: "C4",
    difficulty: "hard",
    type: "calc",
    prompt:
      "CAC = 20 $ et valeur vie client (LTV) = 60 $. Quel est le ratio LTV/CAC, et est-il sain ?",
    options: [
      "0,33 — sain",
      "3 — sain (repère courant ≥ 3)",
      "3 — malsain",
      "1,2 — sain",
    ],
    correct: [1],
    explanation: "LTV/CAC = 60/20 = 3. Un ratio ≥ 3 est généralement considéré comme sain.",
    feedbackOnError: "Ratio = LTV ÷ CAC ; comparez ensuite au repère de 3.",
    tags: ["LTV", "CAC", "calcul"],
    editorialStatus: "approved",
  },
  {
    id: "mkt-v2-m1-q10",
    module: 1,
    week: 2,
    objectiveRef: "C3",
    difficulty: "easy",
    type: "mcq",
    prompt: "Quelle est l'erreur la plus fréquente du marketing digital débutant ?",
    options: [
      "Mesurer trop souvent ses résultats",
      "Choisir un canal parce qu'il est « à la mode » plutôt que parce que le public cible s'y trouve",
      "Créer un persona",
      "Segmenter son audience",
    ],
    correct: [1],
    explanation: "Suivre la mode plutôt que le persona gaspille le budget.",
    feedbackOnError: "Le bon canal est celui où se trouve votre persona, pas le plus tendance.",
    tags: ["canaux", "erreurs"],
    editorialStatus: "approved",
  },
  {
    id: "mkt-v2-m1-q11",
    module: 1,
    week: 1,
    objectiveRef: "C1",
    difficulty: "medium",
    type: "mcq",
    prompt: "Lequel de ces canaux relève typiquement du marketing digital ?",
    options: ["Panneau d'autoroute", "Publicité radio locale", "Référencement sur moteur de recherche (SEO)", "Encart dans un journal papier"],
    correct: [2],
    explanation: "Le SEO est un canal numérique ; les trois autres sont traditionnels.",
    feedbackOnError: "Un canal digital passe par un support numérique mesurable.",
    tags: ["canaux", "définition"],
    editorialStatus: "approved",
  },
  {
    id: "mkt-v2-m1-q12",
    module: 1,
    week: 3,
    objectiveRef: "C4",
    difficulty: "medium",
    type: "interpret",
    prompt:
      "Tableau : Canal A — 100 clics, 5 ventes ; Canal B — 400 clics, 8 ventes. Quel canal a le meilleur taux de conversion ?",
    options: ["Canal A (5 %)", "Canal B (2 %)", "Ils sont égaux", "Impossible à dire"],
    correct: [0],
    explanation: "A = 5/100 = 5 % ; B = 8/400 = 2 %. A convertit mieux malgré moins de clics.",
    feedbackOnError: "Taux de conversion = ventes ÷ clics ; comparez les pourcentages, pas les volumes bruts.",
    tags: ["conversion", "interprétation"],
    editorialStatus: "approved",
  },
  {
    id: "mkt-v2-m1-q13",
    module: 1,
    week: 2,
    objectiveRef: "C3",
    difficulty: "hard",
    type: "analysis",
    prompt:
      "Une PME veut lancer un produit destiné aux 18-24 ans très actifs en vidéo courte. Quel plan de canaux est le plus défendable ?",
    options: [
      "Journaux papier + radio",
      "TikTok/Instagram Reels en priorité, avec mesure du coût par acquisition",
      "Email de masse acheté à un tiers",
      "Uniquement des affiches en magasin",
    ],
    correct: [1],
    explanation:
      "Le persona jeune consomme de la vidéo courte : la priorité va aux plateformes correspondantes, avec suivi du CAC.",
    feedbackOnError: "Alignez le canal sur les habitudes du persona et gardez la mesure.",
    tags: ["canaux", "persona", "analyse"],
    editorialStatus: "approved",
  },
  {
    id: "mkt-v2-m1-q14",
    module: 1,
    week: 1,
    objectiveRef: "C2",
    difficulty: "easy",
    type: "mcq",
    prompt: "Dans le funnel, à quelle étape correspond « transformer un client satisfait en ambassadeur » ?",
    options: ["Acquisition", "Activation", "Recommandation", "Revenu"],
    correct: [2],
    explanation: "La Recommandation transforme les clients en promoteurs de la marque.",
    feedbackOnError: "L'ambassadeur recommande : c'est l'étape Recommandation.",
    tags: ["funnel", "AARRR"],
    editorialStatus: "approved",
  },
  {
    id: "mkt-v2-m1-q15",
    module: 1,
    week: 3,
    objectiveRef: "C4",
    difficulty: "medium",
    type: "mcq",
    prompt: "Quel indicateur mesure directement l'efficacité budgétaire de l'acquisition ?",
    options: ["Nombre d'abonnés", "Coût d'acquisition client (CAC)", "Nombre de « j'aime »", "Nombre de pages du site"],
    correct: [1],
    explanation: "Le CAC relie la dépense au nombre de clients réellement acquis.",
    feedbackOnError: "Cherchez l'indicateur qui rapporte un coût à un résultat client.",
    tags: ["KPI", "CAC"],
    editorialStatus: "approved",
  },
  {
    id: "mkt-v2-m1-q16",
    module: 1,
    week: 2,
    objectiveRef: "C3",
    difficulty: "medium",
    type: "scenario",
    prompt:
      "Julie dépense 600 $/mois sur Facebook « parce que tout le monde en fait ». Quelle est la première action recommandée ?",
    options: [
      "Doubler le budget",
      "Analyser le funnel pour localiser la vraie fuite avant de dépenser plus",
      "Arrêter tout marketing",
      "Changer de logo",
    ],
    correct: [1],
    explanation:
      "Le cas Savonnerie Boréale montre que la fuite était l'Activation ; l'analyse précède toute hausse de budget.",
    feedbackOnError: "Diagnostiquez avant d'investir davantage.",
    tags: ["cas", "diagnostic"],
    editorialStatus: "approved",
  },
  {
    id: "mkt-v2-m1-q17",
    module: 1,
    week: 1,
    objectiveRef: "C1",
    difficulty: "hard",
    type: "analysis",
    prompt: "Pourquoi dit-on que le marketing digital « cesse d'être un pari pour devenir une discipline pilotée par la donnée » ?",
    options: [
      "Parce qu'il est gratuit",
      "Parce qu'on peut attribuer coûts et résultats à chaque canal et étape, et décider sur des faits",
      "Parce qu'il supprime le besoin de stratégie",
      "Parce qu'il garantit le succès",
    ],
    correct: [1],
    explanation: "L'attribution précise des coûts et résultats remplace l'intuition par la décision fondée sur les données.",
    feedbackOnError: "Le pilotage par la donnée repose sur la mesure et l'attribution.",
    tags: ["données", "définition"],
    editorialStatus: "approved",
  },
  {
    id: "mkt-v2-m1-q18",
    module: 1,
    week: 3,
    objectiveRef: "C4",
    difficulty: "easy",
    type: "mcq",
    prompt: "Un « KPI » est :",
    options: [
      "Un indicateur clé de performance",
      "Un type de publicité payante",
      "Un réseau social",
      "Un format d'image",
    ],
    correct: [0],
    explanation: "KPI = Key Performance Indicator, un indicateur clé de performance.",
    feedbackOnError: "KPI mesure la performance d'un objectif.",
    tags: ["KPI", "vocabulaire"],
    editorialStatus: "approved",
  },
  {
    id: "mkt-v2-m1-q19",
    module: 1,
    week: 2,
    objectiveRef: "C3",
    difficulty: "medium",
    type: "multi",
    prompt: "Quelles informations font partie d'un bon persona ? (plusieurs réponses)",
    options: ["Ses freins à l'achat", "Les plateformes qu'il fréquente", "Le chiffre d'affaires du concurrent", "Ses habitudes de consommation"],
    correct: [0, 1, 3],
    explanation: "Le persona décrit le client (freins, plateformes, habitudes), pas les finances d'un concurrent.",
    feedbackOnError: "Un persona reste centré sur le client cible.",
    tags: ["persona", "ciblage"],
    editorialStatus: "approved",
  },
  {
    id: "mkt-v2-m1-q20",
    module: 1,
    week: 3,
    objectiveRef: "C4",
    difficulty: "hard",
    type: "interpret",
    prompt:
      "Deux campagnes : X dépense 1 000 $ pour 25 clients ; Y dépense 1 500 $ pour 50 clients. Laquelle a le meilleur CAC ?",
    options: ["X (40 $)", "Y (30 $)", "Égalité", "X (25 $)"],
    correct: [1],
    explanation: "X : 1000/25 = 40 $ ; Y : 1500/50 = 30 $. Y a le meilleur (plus bas) CAC.",
    feedbackOnError: "Calculez le CAC de chaque campagne puis comparez ; le plus bas est le meilleur.",
    tags: ["CAC", "comparaison", "calcul"],
    editorialStatus: "approved",
  },
];
