import type { BankQuestion } from "@/lib/academic/types";

/**
 * Banque de questions — Marketing Digital v2.
 * ÉTAT : Module 1 rédigé comme exemplaire de référence (20 questions, difficulté et types variés).
 * Modules 2–8 : à rédiger module par module (voir MARKETING_QUESTION_BANK_AUDIT.md).
 *
 * SÉCURITÉ : `correct` ne doit jamais transiter vers le client public — la correction est serveur.
 */
export const marketingDigitalV2Bank: BankQuestion[] = [
  {
    id: "mkt-v2-m1-q01",
    module: 1,
    week: 1,
    objectiveRef: "C1",
    difficulty: "easy",
    type: "mcq",
    prompt: "Qu'est-ce qui distingue fondamentalement le marketing digital du marketing traditionnel ?",
    options: [
      "Il est toujours moins cher",
      "Il permet de mesurer précisément chaque interaction et d'ajuster en temps réel",
      "Il ne nécessite aucune stratégie",
      "Il touche uniquement les jeunes",
    ],
    correct: [1],
    explanation:
      "La mesurabilité et l'agilité (ajustement en temps réel) sont les traits distinctifs, pas le coût ni l'audience.",
    feedbackOnError: "Revoyez la notion de mesurabilité : chaque impression, clic et achat est traçable.",
    tags: ["fondamentaux", "définition"],
    editorialStatus: "approved",
  },
  {
    id: "mkt-v2-m1-q02",
    module: 1,
    week: 1,
    objectiveRef: "C1",
    difficulty: "easy",
    type: "mcq",
    prompt: "Dans le modèle AARRR, que signifie la première lettre « A » ?",
    options: ["Analytics", "Acquisition", "Activation", "Ads"],
    correct: [1],
    explanation: "AARRR = Acquisition, Activation, Rétention, Recommandation, Revenu.",
    feedbackOnError: "La première étape attire du trafic : c'est l'Acquisition.",
    tags: ["funnel", "AARRR"],
    editorialStatus: "approved",
  },
  {
    id: "mkt-v2-m1-q03",
    module: 1,
    week: 1,
    objectiveRef: "C2",
    difficulty: "medium",
    type: "multi",
    prompt: "Parmi les éléments suivants, lesquels appartiennent au modèle AARRR ? (plusieurs réponses)",
    options: ["Rétention", "Recommandation", "Rentabilité brute", "Activation"],
    correct: [0, 1, 3],
    explanation: "AARRR contient Rétention, Recommandation et Activation ; « Rentabilité brute » n'en fait pas partie.",
    feedbackOnError: "Rappelez-vous : Acquisition, Activation, Rétention, Recommandation, Revenu.",
    tags: ["funnel", "AARRR"],
    editorialStatus: "approved",
  },
  {
    id: "mkt-v2-m1-q04",
    module: 1,
    week: 2,
    objectiveRef: "C2",
    difficulty: "medium",
    type: "scenario",
    prompt:
      "Une boutique attire 5 000 visiteurs/mois mais 93 % quittent la fiche produit sans rien ajouter au panier. Où se situe la fuite du funnel ?",
    options: ["Acquisition", "Activation", "Recommandation", "Revenu"],
    correct: [1],
    explanation:
      "Le trafic arrive (Acquisition OK) mais la conversion échoue : la fuite est à l'Activation. Augmenter le budget pub n'y changerait rien.",
    feedbackOnError: "Le trafic est bon ; le problème est la conversion des visiteurs en action.",
    tags: ["funnel", "diagnostic"],
    editorialStatus: "approved",
  },
  {
    id: "mkt-v2-m1-q05",
    module: 1,
    week: 2,
    objectiveRef: "C3",
    difficulty: "medium",
    type: "mcq",
    prompt: "Qu'est-ce qu'un persona en marketing ?",
    options: [
      "Le nom commercial d'un produit",
      "La représentation semi-fictive du client idéal (habitudes, freins, canaux)",
      "Un influenceur payé",
      "Le logo d'une marque",
    ],
    correct: [1],
    explanation: "Le persona synthétise le client idéal pour guider le choix des messages et des canaux.",
    feedbackOnError: "Un persona décrit un type de client, pas un produit ni une marque.",
    tags: ["persona", "ciblage"],
    editorialStatus: "approved",
  },
  {
    id: "mkt-v2-m1-q06",
    module: 1,
    week: 2,
    objectiveRef: "C3",
    difficulty: "hard",
    type: "scenario",
    prompt:
      "Un logiciel B2B à cycle de vente de 4 mois avec plusieurs décideurs. Quelle approche est la plus cohérente ?",
    options: [
      "Une campagne d'achat impulsif sur TikTok",
      "Un contenu éducatif et un nurturing par email/LinkedIn adapté au cycle long",
      "Des soldes flash quotidiennes",
      "Uniquement des publicités display génériques",
    ],
    correct: [1],
    explanation:
      "Un cycle B2B long et multi-décideurs se travaille par contenu de fond et nurturing, pas par l'impulsion.",
    feedbackOnError: "Adaptez le canal et le message au cycle de vente et au persona, pas à la mode.",
    tags: ["persona", "B2B", "canaux"],
    editorialStatus: "approved",
  },
  {
    id: "mkt-v2-m1-q07",
    module: 1,
    week: 1,
    objectiveRef: "C2",
    difficulty: "easy",
    type: "mcq",
    prompt: "Pourquoi attirer davantage de trafic est-il inutile si le site ne convertit pas ?",
    options: [
      "Parce que le trafic coûte cher",
      "Parce que la fuite du funnel est en aval : plus de visiteurs = plus de pertes au même endroit",
      "Parce que Google le pénalise",
      "Parce que le trafic ralentit le site",
    ],
    correct: [1],
    explanation: "On corrige d'abord l'étape qui fuit ; sinon on amplifie simplement la perte.",
    feedbackOnError: "Identifiez l'étape qui fuit avant d'investir en amont.",
    tags: ["funnel", "priorisation"],
    editorialStatus: "approved",
  },
  {
    id: "mkt-v2-m1-q08",
    module: 1,
    week: 3,
    objectiveRef: "C4",
    difficulty: "medium",
    type: "calc",
    prompt:
      "Une campagne coûte 800 $ et génère 40 nouveaux clients. Quel est le coût d'acquisition client (CAC) ?",
    options: ["20 $", "32 $", "40 $", "80 $"],
    correct: [0],
    explanation: "CAC = dépense / clients acquis = 800 / 40 = 20 $.",
    feedbackOnError: "CAC = coût total ÷ nombre de clients acquis.",
    tags: ["CAC", "calcul"],
    editorialStatus: "approved",
  },
  {
    id: "mkt-v2-m1-q09",
    module: 1,
    week: 3,
    objectiveRef: "C4",
    difficulty: "hard",
    type: "calc",
    prompt:
      "CAC = 20 $ et valeur vie client (LTV) = 60 $. Quel est le ratio LTV/CAC, et est-il sain ?",
    options: [
      "0,33 — sain",
      "3 — sain (repère courant ≥ 3)",
      "3 — malsain",
      "1,2 — sain",
    ],
    correct: [1],
    explanation: "LTV/CAC = 60/20 = 3. Un ratio ≥ 3 est généralement considéré comme sain.",
    feedbackOnError: "Ratio = LTV ÷ CAC ; comparez ensuite au repère de 3.",
    tags: ["LTV", "CAC", "calcul"],
    editorialStatus: "approved",
  },
  {
    id: "mkt-v2-m1-q10",
    module: 1,
    week: 2,
    objectiveRef: "C3",
    difficulty: "easy",
    type: "mcq",
    prompt: "Quelle est l'erreur la plus fréquente du marketing digital débutant ?",
    options: [
      "Mesurer trop souvent ses résultats",
      "Choisir un canal parce qu'il est « à la mode » plutôt que parce que le public cible s'y trouve",
      "Créer un persona",
      "Segmenter son audience",
    ],
    correct: [1],
    explanation: "Suivre la mode plutôt que le persona gaspille le budget.",
    feedbackOnError: "Le bon canal est celui où se trouve votre persona, pas le plus tendance.",
    tags: ["canaux", "erreurs"],
    editorialStatus: "approved",
  },
  {
    id: "mkt-v2-m1-q11",
    module: 1,
    week: 1,
    objectiveRef: "C1",
    difficulty: "medium",
    type: "mcq",
    prompt: "Lequel de ces canaux relève typiquement du marketing digital ?",
    options: ["Panneau d'autoroute", "Publicité radio locale", "Référencement sur moteur de recherche (SEO)", "Encart dans un journal papier"],
    correct: [2],
    explanation: "Le SEO est un canal numérique ; les trois autres sont traditionnels.",
    feedbackOnError: "Un canal digital passe par un support numérique mesurable.",
    tags: ["canaux", "définition"],
    editorialStatus: "approved",
  },
  {
    id: "mkt-v2-m1-q12",
    module: 1,
    week: 3,
    objectiveRef: "C4",
    difficulty: "medium",
    type: "interpret",
    prompt:
      "Tableau : Canal A — 100 clics, 5 ventes ; Canal B — 400 clics, 8 ventes. Quel canal a le meilleur taux de conversion ?",
    options: ["Canal A (5 %)", "Canal B (2 %)", "Ils sont égaux", "Impossible à dire"],
    correct: [0],
    explanation: "A = 5/100 = 5 % ; B = 8/400 = 2 %. A convertit mieux malgré moins de clics.",
    feedbackOnError: "Taux de conversion = ventes ÷ clics ; comparez les pourcentages, pas les volumes bruts.",
    tags: ["conversion", "interprétation"],
    editorialStatus: "approved",
  },
  {
    id: "mkt-v2-m1-q13",
    module: 1,
    week: 2,
    objectiveRef: "C3",
    difficulty: "hard",
    type: "analysis",
    prompt:
      "Une PME veut lancer un produit destiné aux 18-24 ans très actifs en vidéo courte. Quel plan de canaux est le plus défendable ?",
    options: [
      "Journaux papier + radio",
      "TikTok/Instagram Reels en priorité, avec mesure du coût par acquisition",
      "Email de masse acheté à un tiers",
      "Uniquement des affiches en magasin",
    ],
    correct: [1],
    explanation:
      "Le persona jeune consomme de la vidéo courte : la priorité va aux plateformes correspondantes, avec suivi du CAC.",
    feedbackOnError: "Alignez le canal sur les habitudes du persona et gardez la mesure.",
    tags: ["canaux", "persona", "analyse"],
    editorialStatus: "approved",
  },
  {
    id: "mkt-v2-m1-q14",
    module: 1,
    week: 1,
    objectiveRef: "C2",
    difficulty: "easy",
    type: "mcq",
    prompt: "Dans le funnel, à quelle étape correspond « transformer un client satisfait en ambassadeur » ?",
    options: ["Acquisition", "Activation", "Recommandation", "Revenu"],
    correct: [2],
    explanation: "La Recommandation transforme les clients en promoteurs de la marque.",
    feedbackOnError: "L'ambassadeur recommande : c'est l'étape Recommandation.",
    tags: ["funnel", "AARRR"],
    editorialStatus: "approved",
  },
  {
    id: "mkt-v2-m1-q15",
    module: 1,
    week: 3,
    objectiveRef: "C4",
    difficulty: "medium",
    type: "mcq",
    prompt: "Quel indicateur mesure directement l'efficacité budgétaire de l'acquisition ?",
    options: ["Nombre d'abonnés", "Coût d'acquisition client (CAC)", "Nombre de « j'aime »", "Nombre de pages du site"],
    correct: [1],
    explanation: "Le CAC relie la dépense au nombre de clients réellement acquis.",
    feedbackOnError: "Cherchez l'indicateur qui rapporte un coût à un résultat client.",
    tags: ["KPI", "CAC"],
    editorialStatus: "approved",
  },
  {
    id: "mkt-v2-m1-q16",
    module: 1,
    week: 2,
    objectiveRef: "C3",
    difficulty: "medium",
    type: "scenario",
    prompt:
      "Julie dépense 600 $/mois sur Facebook « parce que tout le monde en fait ». Quelle est la première action recommandée ?",
    options: [
      "Doubler le budget",
      "Analyser le funnel pour localiser la vraie fuite avant de dépenser plus",
      "Arrêter tout marketing",
      "Changer de logo",
    ],
    correct: [1],
    explanation:
      "Le cas Savonnerie Boréale montre que la fuite était l'Activation ; l'analyse précède toute hausse de budget.",
    feedbackOnError: "Diagnostiquez avant d'investir davantage.",
    tags: ["cas", "diagnostic"],
    editorialStatus: "approved",
  },
  {
    id: "mkt-v2-m1-q17",
    module: 1,
    week: 1,
    objectiveRef: "C1",
    difficulty: "hard",
    type: "analysis",
    prompt: "Pourquoi dit-on que le marketing digital « cesse d'être un pari pour devenir une discipline pilotée par la donnée » ?",
    options: [
      "Parce qu'il est gratuit",
      "Parce qu'on peut attribuer coûts et résultats à chaque canal et étape, et décider sur des faits",
      "Parce qu'il supprime le besoin de stratégie",
      "Parce qu'il garantit le succès",
    ],
    correct: [1],
    explanation: "L'attribution précise des coûts et résultats remplace l'intuition par la décision fondée sur les données.",
    feedbackOnError: "Le pilotage par la donnée repose sur la mesure et l'attribution.",
    tags: ["données", "définition"],
    editorialStatus: "approved",
  },
  {
    id: "mkt-v2-m1-q18",
    module: 1,
    week: 3,
    objectiveRef: "C4",
    difficulty: "easy",
    type: "mcq",
    prompt: "Un « KPI » est :",
    options: [
      "Un indicateur clé de performance",
      "Un type de publicité payante",
      "Un réseau social",
      "Un format d'image",
    ],
    correct: [0],
    explanation: "KPI = Key Performance Indicator, un indicateur clé de performance.",
    feedbackOnError: "KPI mesure la performance d'un objectif.",
    tags: ["KPI", "vocabulaire"],
    editorialStatus: "approved",
  },
  {
    id: "mkt-v2-m1-q19",
    module: 1,
    week: 2,
    objectiveRef: "C3",
    difficulty: "medium",
    type: "multi",
    prompt: "Quelles informations font partie d'un bon persona ? (plusieurs réponses)",
    options: ["Ses freins à l'achat", "Les plateformes qu'il fréquente", "Le chiffre d'affaires du concurrent", "Ses habitudes de consommation"],
    correct: [0, 1, 3],
    explanation: "Le persona décrit le client (freins, plateformes, habitudes), pas les finances d'un concurrent.",
    feedbackOnError: "Un persona reste centré sur le client cible.",
    tags: ["persona", "ciblage"],
    editorialStatus: "approved",
  },
  {
    id: "mkt-v2-m1-q20",
    module: 1,
    week: 3,
    objectiveRef: "C4",
    difficulty: "hard",
    type: "interpret",
    prompt:
      "Deux campagnes : X dépense 1 000 $ pour 25 clients ; Y dépense 1 500 $ pour 50 clients. Laquelle a le meilleur CAC ?",
    options: ["X (40 $)", "Y (30 $)", "Égalité", "X (25 $)"],
    correct: [1],
    explanation: "X : 1000/25 = 40 $ ; Y : 1500/50 = 30 $. Y a le meilleur (plus bas) CAC.",
    feedbackOnError: "Calculez le CAC de chaque campagne puis comparez ; le plus bas est le meilleur.",
    tags: ["CAC", "comparaison", "calcul"],
    editorialStatus: "approved",
  },

  // ═══════════════════ MODULE 2 — 20 questions (semaines 4–6) ═══════════════════
  // Recherche de marché (C5) : q01–q05
  {
    id: "mkt-v2-m2-q01",
    module: 2,
    week: 4,
    objectiveRef: "C5",
    difficulty: "easy",
    type: "mcq",
    prompt: "Quelles conditions sont nécessaires pour qu'un marché existe réellement ?",
    options: [
      "Un besoin, un pouvoir d'achat et une volonté d'agir",
      "Uniquement beaucoup de personnes intéressées",
      "Un produit tendance",
      "Une grande page de réseau social",
    ],
    correct: [0],
    explanation: "Un marché exige un besoin réel, la capacité de payer (solvabilité) et la volonté d'agir.",
    feedbackOnError: "Un besoin non solvable ou sans volonté d'achat n'est pas un marché.",
    tags: ["marché", "définition"],
    editorialStatus: "approved",
  },
  {
    id: "mkt-v2-m2-q02",
    module: 2,
    week: 4,
    objectiveRef: "C5",
    difficulty: "medium",
    type: "scenario",
    prompt:
      "Un entrepreneur affirme : « Mon marché fait 5 milliards, il me suffit d'en prendre 1 %. » Quel est le problème principal de ce raisonnement ?",
    options: [
      "Il sous-estime son marché",
      "Il confond le marché total (TAM) avec ce qu'il peut réellement capter (SOM), en ignorant l'accessibilité",
      "Il calcule mal le pourcentage",
      "Aucun problème, c'est un bon plan",
    ],
    correct: [1],
    explanation: "Sans canal, budget ni différenciation, ce 1 % est théorique. On planifie en SOM, pas en TAM.",
    feedbackOnError: "Revoyez la distinction TAM/SAM/SOM et la notion d'accessibilité.",
    tags: ["TAM", "SOM", "attractivité"],
    editorialStatus: "approved",
  },
  {
    id: "mkt-v2-m2-q03",
    module: 2,
    week: 4,
    objectiveRef: "C5",
    difficulty: "medium",
    type: "mcq",
    prompt: "Laquelle de ces sources est une donnée PRIMAIRE ?",
    options: [
      "Un rapport de Statistique Canada",
      "Un article sectoriel publié en ligne",
      "Des entretiens que vous menez vous-même avec 8 clients",
      "Les avis publiés sur une marketplace",
    ],
    correct: [2],
    explanation: "Les données primaires sont collectées par vous-même ; les trois autres existent déjà (secondaires).",
    feedbackOnError: "Primaire = collectée par vous ; secondaire = déjà existante.",
    tags: ["recherche", "primaire-secondaire"],
    editorialStatus: "approved",
  },
  {
    id: "mkt-v2-m2-q04",
    module: 2,
    week: 4,
    objectiveRef: "C5",
    difficulty: "medium",
    type: "scenario",
    prompt:
      "Un sondage demande : « Ne trouvez-vous pas que notre service est rapide et abordable ? » Quels défauts cette question cumule-t-elle ?",
    options: [
      "Aucun, la question est claire",
      "Elle est orientée ET double (deux idées en une)",
      "Elle est trop courte",
      "Elle manque d'options de réponse",
    ],
    correct: [1],
    explanation: "« Ne trouvez-vous pas » oriente la réponse, et « rapide et abordable » mêle deux idées : question orientée et double.",
    feedbackOnError: "Une bonne question est neutre et porte sur une seule idée.",
    tags: ["biais", "questionnaire"],
    editorialStatus: "approved",
  },
  {
    id: "mkt-v2-m2-q05",
    module: 2,
    week: 4,
    objectiveRef: "C5",
    difficulty: "hard",
    type: "interpret",
    prompt:
      "78 % des répondants à un sondage disent qu'ils « paieraient pour un nouveau service », mais après le lancement presque personne n'achète. Quelle leçon en tirer ?",
    options: [
      "Le service était mal conçu",
      "L'intention déclarée ne prédit pas fiablement le comportement réel ; il faut croiser déclaratif et comportement",
      "Le sondage aurait dû avoir plus de répondants",
      "Les gens ont menti volontairement",
    ],
    correct: [1],
    explanation: "Les gens disent « oui » facilement à une question hypothétique ; on valide par un comportement réel (test, pré-achat).",
    feedbackOnError: "Rappelez-vous l'écart entre ce que les gens disent et ce qu'ils font.",
    tags: ["déclaratif", "comportement", "validation"],
    editorialStatus: "approved",
  },
  // Segmentation (C6) : q06–q09
  {
    id: "mkt-v2-m2-q06",
    module: 2,
    week: 5,
    objectiveRef: "C6",
    difficulty: "easy",
    type: "mcq",
    prompt: "Quel est le principal défaut d'un segment défini comme « femmes de 25 à 45 ans » ?",
    options: [
      "Il est trop précis",
      "Il n'est pas actionnable : il mélange des besoins, budgets et modes de vie très différents",
      "Il est illégal",
      "Il est trop petit",
    ],
    correct: [1],
    explanation: "Un simple découpage démographique large n'est pas actionnable ; il faut combiner d'autres critères.",
    feedbackOnError: "Un bon segment est actionnable : on peut lui proposer un message et une offre spécifiques.",
    tags: ["segmentation", "actionnable"],
    editorialStatus: "approved",
  },
  {
    id: "mkt-v2-m2-q07",
    module: 2,
    week: 5,
    objectiveRef: "C6",
    difficulty: "medium",
    type: "multi",
    prompt: "Quels critères parmi les suivants relèvent de la segmentation ? (plusieurs réponses)",
    options: ["Psychographique (valeurs, mode de vie)", "Comportementale (fréquence d'achat)", "Le logo de l'entreprise", "Technographique (appareils, plateformes)"],
    correct: [0, 1, 3],
    explanation: "Psychographique, comportementale et technographique sont des critères de segmentation ; le logo n'en est pas un.",
    feedbackOnError: "La segmentation combine des critères sur les clients, pas sur la marque.",
    tags: ["segmentation", "critères"],
    editorialStatus: "approved",
  },
  {
    id: "mkt-v2-m2-q08",
    module: 2,
    week: 5,
    objectiveRef: "C6",
    difficulty: "medium",
    type: "mcq",
    prompt: "Quelles sont les quatre qualités d'un bon segment ?",
    options: [
      "Mesurable, accessible, substantiel, actionnable",
      "Grand, ancien, connu, populaire",
      "Gratuit, rapide, local, tendance",
      "Jeune, urbain, connecté, riche",
    ],
    correct: [0],
    explanation: "Un segment utile est mesurable, accessible, substantiel (assez gros) et actionnable.",
    feedbackOnError: "Rappelez-vous les 4 qualités : mesurable, accessible, substantiel, actionnable.",
    tags: ["segmentation", "qualité"],
    editorialStatus: "approved",
  },
  {
    id: "mkt-v2-m2-q09",
    module: 2,
    week: 5,
    objectiveRef: "C6",
    difficulty: "hard",
    type: "scenario",
    prompt:
      "Un studio de photo peut servir familles, PME et mariages. Avec un budget limité, quel principe doit guider le choix du segment cible ?",
    options: [
      "Choisir le plus grand segment quoi qu'il arrive",
      "Choisir le segment le plus attractif ET que l'on a la meilleure capacité à servir",
      "Servir les trois en même temps",
      "Choisir au hasard",
    ],
    correct: [1],
    explanation: "La cible est le segment où l'on peut gagner : attractivité croisée avec la capacité à le servir.",
    feedbackOnError: "La cible n'est pas le plus gros segment, mais celui où l'on a les meilleures chances.",
    tags: ["segmentation", "priorisation"],
    editorialStatus: "approved",
  },
  // Personas & JTBD (C6) : q10–q12
  {
    id: "mkt-v2-m2-q10",
    module: 2,
    week: 5,
    objectiveRef: "C6",
    difficulty: "medium",
    type: "mcq",
    prompt: "Qu'est-ce qui distingue un persona d'un stéréotype ?",
    options: [
      "Le persona a une photo",
      "Le persona est fondé sur des données réelles, le stéréotype sur des préjugés non vérifiés",
      "Le persona est toujours plus jeune",
      "Il n'y a aucune différence",
    ],
    correct: [1],
    explanation: "La différence tient à la source : données vérifiées (persona) vs suppositions (stéréotype).",
    feedbackOnError: "Un persona s'appuie sur des faits ; un stéréotype sur des préjugés.",
    tags: ["persona", "stéréotype"],
    editorialStatus: "approved",
  },
  {
    id: "mkt-v2-m2-q11",
    module: 2,
    week: 5,
    objectiveRef: "C6",
    difficulty: "medium",
    type: "analysis",
    prompt:
      "Dans une fiche persona, vous ajoutez « salaire exact de 62 400 $ » sans aucune donnée à l'appui. Pourquoi est-ce problématique ?",
    options: [
      "C'est trop précis pour être utile",
      "Cela crée une fausse précision qui trompe l'équipe ; mieux vaut une fourchette honnête ou une hypothèse marquée",
      "Les salaires ne doivent jamais figurer",
      "Ce n'est pas problématique",
    ],
    correct: [1],
    explanation: "Inventer des chiffres précis donne une illusion de rigueur ; on marque les hypothèses ou on donne une fourchette.",
    feedbackOnError: "Évitez la fausse précision : distinguez données et hypothèses.",
    tags: ["persona", "fausse-précision"],
    editorialStatus: "approved",
  },
  {
    id: "mkt-v2-m2-q12",
    module: 2,
    week: 5,
    objectiveRef: "C6",
    difficulty: "medium",
    type: "mcq",
    prompt: "Dans l'approche Jobs-to-be-Done, que signifie le « travail émotionnel » ?",
    options: [
      "La tâche concrète à accomplir",
      "Ce que le client veut ressentir (sécurité, fierté, sérénité)",
      "L'image projetée auprès des autres",
      "Le prix du produit",
    ],
    correct: [1],
    explanation: "Le travail émotionnel est le ressenti visé ; le fonctionnel est la tâche, le social est l'image projetée.",
    feedbackOnError: "Fonctionnel = tâche ; émotionnel = ressenti ; social = image.",
    tags: ["JTBD", "besoins"],
    editorialStatus: "approved",
  },
  // Concurrence (C7) : q13–q15
  {
    id: "mkt-v2-m2-q13",
    module: 2,
    week: 6,
    objectiveRef: "C7",
    difficulty: "easy",
    type: "mcq",
    prompt: "Un concurrent INDIRECT est :",
    options: [
      "Une entreprise offrant exactement le même produit",
      "Une solution différente qui répond au même besoin (job) du client",
      "Un fournisseur",
      "Un client insatisfait",
    ],
    correct: [1],
    explanation: "Le concurrent indirect résout le même job autrement ; le direct offre une solution similaire.",
    feedbackOnError: "Pensez « même besoin, solution différente » pour l'indirect.",
    tags: ["concurrence", "indirect"],
    editorialStatus: "approved",
  },
  {
    id: "mkt-v2-m2-q14",
    module: 2,
    week: 6,
    objectiveRef: "C7",
    difficulty: "medium",
    type: "scenario",
    prompt:
      "Les ventes matinales d'un café baissent alors que ses deux concurrents directs sont stables. Qu'a-t-il probablement négligé ?",
    options: [
      "Ses concurrents directs",
      "Les concurrents indirects et substituts (dépanneur à 1 $, café maison en télétravail)",
      "Son logo",
      "Le prix de ses grains",
    ],
    correct: [1],
    explanation: "La vraie concurrence incluait des indirects et des substituts hors du radar habituel.",
    feedbackOnError: "N'oubliez pas les concurrents indirects et les solutions de substitution.",
    tags: ["concurrence", "substituts"],
    editorialStatus: "approved",
  },
  {
    id: "mkt-v2-m2-q15",
    module: 2,
    week: 6,
    objectiveRef: "C7",
    difficulty: "medium",
    type: "mcq",
    prompt: "Qu'est-ce qu'un benchmark éthique ?",
    options: [
      "Copier secrètement les fichiers internes d'un concurrent",
      "Comparer à partir d'informations publiques et légitimes (sites, avis, tarifs affichés)",
      "Se faire passer pour un client pour obtenir des données privées",
      "Diffuser de fausses informations sur un concurrent",
    ],
    correct: [1],
    explanation: "Le benchmark éthique s'appuie sur des informations publiques, sans manœuvre trompeuse ni intrusion.",
    feedbackOnError: "Comparer à partir de sources publiques est éthique ; l'espionnage ne l'est pas.",
    tags: ["concurrence", "éthique"],
    editorialStatus: "approved",
  },
  // SWOT (C7) : q16–q17
  {
    id: "mkt-v2-m2-q16",
    module: 2,
    week: 6,
    objectiveRef: "C7",
    difficulty: "medium",
    type: "scenario",
    prompt: "Dans une SWOT, où classer « une nouvelle réglementation favorable au secteur » ?",
    options: ["Force (interne)", "Faiblesse (interne)", "Opportunité (externe)", "Menace (externe)"],
    correct: [2],
    explanation: "Une réglementation vient du marché/environnement : c'est un facteur externe favorable, donc une opportunité.",
    feedbackOnError: "Forces/faiblesses = interne ; opportunités/menaces = externe.",
    tags: ["SWOT", "interne-externe"],
    editorialStatus: "approved",
  },
  {
    id: "mkt-v2-m2-q17",
    module: 2,
    week: 6,
    objectiveRef: "C7",
    difficulty: "hard",
    type: "analysis",
    prompt: "Qu'est-ce qui rend une SWOT réellement utile plutôt qu'une simple liste ?",
    options: [
      "Avoir le plus d'éléments possible par case",
      "Des facteurs précis et étayés, priorisés, puis CROISÉS pour produire des décisions",
      "Utiliser de belles couleurs",
      "La remplir rapidement sans recherche",
    ],
    correct: [1],
    explanation: "La valeur vient du croisement (F×O, f×M…) qui transforme le constat en décisions, sur des faits priorisés.",
    feedbackOnError: "Une SWOT utile est précise, priorisée et croisée.",
    tags: ["SWOT", "croisement"],
    editorialStatus: "approved",
  },
  // Proposition de valeur & positionnement (C7) : q18–q20
  {
    id: "mkt-v2-m2-q18",
    module: 2,
    week: 6,
    objectiveRef: "C7",
    difficulty: "medium",
    type: "scenario",
    prompt: "Laquelle est la MEILLEURE proposition de valeur ?",
    options: [
      "« Des produits de qualité à prix imbattables »",
      "« La solution innovante pour votre bien-être »",
      "« Pour les parents pressés, nos repas prêts en 5 min sont approuvés par une nutritionniste, sans additifs »",
      "« Le meilleur choix du marché »",
    ],
    correct: [2],
    explanation: "Elle cible un segment précis, promet un bénéfice concret, apporte une preuve (nutritionniste) et une différence (sans additifs).",
    feedbackOnError: "Une bonne proposition est spécifique, prouvée et différenciante.",
    tags: ["proposition-valeur"],
    editorialStatus: "approved",
  },
  {
    id: "mkt-v2-m2-q19",
    module: 2,
    week: 6,
    objectiveRef: "C7",
    difficulty: "medium",
    type: "truefalse",
    prompt: "Vrai ou faux (raisonné) : « Une promesse marketing forte peut se passer de preuve tant qu'elle est bien formulée. »",
    options: [
      "Vrai — le style suffit à convaincre",
      "Faux — sans preuve (chiffre, garantie, témoignage), une promesse n'est qu'un slogan peu crédible",
      "Vrai — les clients ne vérifient jamais",
      "Faux — il ne faut jamais faire de promesse",
    ],
    correct: [1],
    explanation: "La preuve (raison de croire) rend la promesse crédible ; sans elle, ce n'est qu'un slogan.",
    feedbackOnError: "Une promesse sans preuve manque de crédibilité.",
    tags: ["proposition-valeur", "preuve"],
    editorialStatus: "approved",
  },
  {
    id: "mkt-v2-m2-q20",
    module: 2,
    week: 6,
    objectiveRef: "C7",
    difficulty: "hard",
    type: "scenario",
    prompt:
      "Une entreprise se positionne comme « la plateforme tout-en-un pour toutes les entreprises » et peine à vendre. Quelle correction est la plus solide ?",
    options: [
      "Baisser les prix",
      "Assumer un choix : cibler un segment précis avec une promesse et une différence claires",
      "Ajouter encore plus de fonctionnalités",
      "Changer de logo",
    ],
    correct: [1],
    explanation: "Un positionnement fort assume un choix (cible, promesse, différence) plutôt que de viser « tout le monde ».",
    feedbackOnError: "« Tout pour tous » n'occupe aucune place claire ; il faut assumer un choix.",
    tags: ["positionnement"],
    editorialStatus: "approved",
  },
];
